window.HALO_V5_PAGES = [
  {
    "id": "SYS-01",
    "group": "首次使用",
    "name": "启动与会话恢复",
    "route": "App Launch",
    "priority": "P0",
    "parent": "系统",
    "function": "恢复会话并路由到正确起点",
    "layout": "复用欢迎页正式超级符号和 Logo；正常无按钮，等待较久才补短提示；不显示虚构百分比",
    "data": "startup attempt ID、绝对开始/完成时间、状态/目标；既有模拟登录、上次页面、连接引导、基础资料及用户记录",
    "interaction": "正常自动恢复；失败重试；离线仅在已登录且有保存记录时可只读查看；登录过期重新登录",
    "logic": "无 hash 从启动页进入；注销处理中优先回进度，购买意图保留，未完成连接/基础资料回对应步骤，其余恢复有效页面；访客不进入主界面；替换历史避免返回启动页循环",
    "exception": "慢加载、恢复失败、无网络、登录过期；刷新按同一尝试和截止时间恢复；离开页面后不被回调拉回；重试不删除草稿或业务资产",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "SYS-01 逐页本地实施：桌面右侧审阅状态不进入手机界面；会话/延迟为模拟，真实服务端校验和原生离线缓存仍需接入；不把演示健康值当离线记录"
  },
  {
    "id": "ONB-01",
    "group": "首次使用",
    "name": "欢迎使用 Halo",
    "route": "`/onboarding/intro`",
    "priority": "P0",
    "parent": "SYS-01",
    "function": "品牌欢迎与统一登录入口",
    "layout": "正式超级符号、官方 Logo、底部登录主按钮，以及同宽描边购买次按钮",
    "data": "本地品牌素材；不展示健康数值、功能介绍或规则说明",
    "interaction": "登录进入 AUTH-01；整块“还没有 Halo Ring？立即购买”按钮打开 SEL-03 的智能戒指详情，未登录也可浏览；品牌图形不作点击入口",
    "logic": "下单与加入购物车需登录，AUTH-01 同页登录成功后返回原商品；登录前不请求蓝牙、通知和健康权限",
    "exception": "离线仍可查看本地欢迎内容；小屏与大字号可滚动，不遮挡主按钮",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07 欢迎页经用户确认后，按最新要求将购买小字改成独立按钮；品牌与登录主按钮保留，购买去向不变。AUTH-01 已确认原型不变"
  },
  {
    "id": "AUTH-01",
    "group": "首次使用",
    "name": "手机号登录",
    "route": "`/auth/login`",
    "priority": "P0",
    "parent": "ONB-01 / SEL-03",
    "function": "手机号与验证码同页登录；新账号由服务端自动创建，不另设注册入口",
    "layout": "返回、手机号登录标题、+86 手机号、验证码及右侧获取按钮；一个勾选项统一同意用户协议、隐私政策和 AI 服务说明，三份独立阅读；登录主按钮",
    "data": "authForm 草稿/consentScope、手机号绑定请求、时效/重发截止时间、登录尝试 ID/结果；agreementAcceptance 记录来源、三份说明、范围与时间；authReturnRoute 返回意图",
    "interaction": "获取验证码不跳页；输入六位且勾选三份说明后点击登录；阅读不自动勾选，关闭阅读返回原表单并保留输入；发送/登录中反馈与就地重试",
    "logic": "明确勾选后登录成功，统一记录三份说明同意；新用户进入 ONB-03、老用户回今日、购买意图回原商品；不再要求独立 AI 同意，不改变身体数据/记忆/主动消息开关；新旧账号识别在后台完成",
    "exception": "号码无效、未勾选、发送/登录中、倒计时、网络失败、请求过多、错码、过期、五次错码后重取；草稿/异步请求跨刷新恢复，修改号码使旧码失效",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "账号/验证码",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07 按用户最新要求并入 AI 服务说明，保留已确认登录版式。旧两份协议的缓存勾选不自动扩展，需显式重勾；旧有效会话与资产不清空。正式三份文本、合并同意适用性及服务端版本留痕待审定"
  },
  {
    "id": "AUTH-02",
    "group": "首次使用",
    "name": "验证码（已合入登录页）",
    "route": "`/auth/otp`",
    "priority": "P0",
    "parent": "AUTH-01",
    "function": "兼容旧页面 ID，实际打开 AUTH-01 同页验证码区域",
    "layout": "不再作为独立页面展示；输入、倒计时和错误就地呈现",
    "data": "共用 AUTH-01 的 authForm，不维护另一套验证码状态",
    "interaction": "旧深链与目录入口统一归并 AUTH-01；不增加额外确认步骤",
    "logic": "旧版缺少手机号绑定挑战及时效的请求失效，保留号码与勾选草稿",
    "exception": "旧请求重新获取；受同一登录状态机约束",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "账号/验证码",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07 用户明确要求合入 AUTH-01；保留 ID 便于历史规格和链接兼容"
  },
  {
    "id": "LEGAL-01",
    "group": "首次使用",
    "name": "协议与说明",
    "route": "`/legal/consent`",
    "priority": "P0",
    "parent": "LEGAL-02；AUTH-01 直接复用阅读层",
    "function": "保留三份协议与说明的只读查阅页，不再单独收集同意",
    "layout": "短标题、三份阅读入口、一句健康边界和原型摘要标识；阅读层固定标题/关闭和返回，正文单独滚动；无同意开关、确认提示或登录后关卡",
    "data": "history.state.legalReading 仅保存 kind/route/top；不新增业务字段或写入同意、权限和资产；正式协议 ID/版本及正文待法务与后端接入",
    "interaction": "我的→关于与协议→协议与说明；阅读不改勾选，关闭/Escape/浏览器返回先关阅读并回焦；刷新与前进恢复文档和位置，页面返回原入口，直接深链返回关于与协议",
    "logic": "用户协议、隐私政策和 AI 服务说明均在 AUTH-01 一个勾选项确认；未登录旧深链回登录，已登录只读；旧会话未确认 AI 时不伪造确认状态",
    "exception": "旧会话未确认、未登录深链、无效阅读状态、跨页历史跳转、窄屏/短屏；注销处理中在关于页保留三份直读入口，不被新路由门禁挡住",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07 LEGAL-01 逐页审评：7.0→9.0/10，修改后原型已获用户确认。保留页面 ID、旧路由、AUTH-01 三份合并勾选与现有摘要，不代表正式法律文本或合规验收。LEGAL-02、PERM-01 后续审评已完成，以各页最新记录为准。旧 legal-continue 仅返回"
  },
  {
    "id": "ONB-03",
    "group": "首次使用",
    "name": "连接你的 Halo Ring",
    "route": "`/onboarding/connect`",
    "priority": "P0",
    "parent": "AUTH-01 首次登录",
    "function": "首次登录后选择连接戒指，或暂不连接直接进入 App",
    "layout": "保留瓷白戒指图、连接标题和一句说明；连接主按钮、同宽描边次按钮“暂不连接，先看看”；小字说明以后可在我的连接",
    "data": "connectionIntro.choice/completed/returnRoute；本页不请求蓝牙、不修改既有权限、设备和会员资产",
    "interaction": "连接直达 DEV-01；其返回键回 ONB-03 重新选择，不误跳我的或默认跳过；暂不连接回今日（仍经既有资料等门控），替换引导历史条目",
    "logic": "进入 DEV-01 或明确跳过完成本页选择，不等于绑定激活；从 DEV-01 返回后重新选择，不能记作跳过；首次、已绑定及未允许蓝牙时连接都去 DEV-01；蓝牙检查留在 DEV-01",
    "exception": "未选择就刷新仍停留；返回引导后已发起的权限结果仍可保存，但不完成引导、不自动跳页；returnRoute 持久保存，刷新或启动恢复后可回引导；从我的连接不误回引导；未登录深链拦截",
    "ios": "蓝牙授权与开关状态以系统回调为准；本地原型仅模拟",
    "android": "蓝牙/附近设备权限按实际系统版本适配；本地原型仅模拟",
    "sdk": "本页仅导航，不调用 SDK；DEV-01 按需使用系统蓝牙权限与连接能力",
    "rules": "先说明用途再请求；允许权限不等于设备已绑定或已产生健康数据",
    "backend": "本页不创建绑定；后续设备流程沿用原实现",
    "owner": "产品+UI+双端",
    "source": "2026-09-07 用户逐页审阅反馈；现有品牌素材与首次使用流程",
    "note": "用户已确认本地可交互原型；真实权限未接入，不新增一级入口"
  },
  {
    "id": "PERM-01",
    "group": "首次使用",
    "name": "系统权限",
    "route": "`/permissions`",
    "priority": "P0",
    "parent": "设置 / 设备与提醒异常入口",
    "function": "查看权限用途和已有状态，按需管理，不作为连接或登录必经关卡",
    "layout": "保留蓝牙与通知行；新增手机系统健康只读入口，复用范围/系统模拟/结果/帮助/清除弹层；不新增一级入口或伪授权开关",
    "data": "复用既有蓝牙/通知状态；新增 systemHealth.version/accounts[账号]：provider、requested、mockReadChoices、enabled、promptedAt、lastReadAt、request 与独立 simulated records；不写旧 healthAccess",
    "interaction": "手机系统健康→选择步数/睡眠/心率→明确模拟系统授权→手动读取→带来源结果；管理范围、停止读取、确认清除；设置/设备/提醒来源返回契约保留",
    "logic": "未绑定也可单独读取；选择范围不等于系统授权，授权完成不等于读到全部项目；无记录不推断 Apple 拒绝；不写入手机健康；不融合戒指/Body Weather/AI或会员成长；请求按账号+平台+ID校验，同源记录替换去重",
    "exception": "取消不改设置，部分可读/全无数据/失败/系统访问变化/平台不支持；保存失败保留旧记录并重试同请求；刷新恢复不跳页；停止保留副本，清除不删手机源；账号隔离、损坏记录过滤、短屏滚动",
    "ios": "原型模拟 Apple 健康；真实读取需原生 HealthKit 能力、用途说明和按类型授权。不能通过空结果判定读权限被拒绝，不申请写入",
    "android": "原型模拟 Health Connect；正式版需检查可用性、按类型读取权限，步数通过平台聚合避免多来源重复；本轮不申请后台读取",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07 用户已确认新增手机系统健康只读流程，原暂未接入说明被替代。步数/睡眠/心率为本轮示例范围，生产白名单/融合口径未冻结。全部为示例，无真实系统 API 或健康文件读取；失败/平台模拟仅在App外审阅区。不恢复旧健康单次明确授权规则"
  },
  {
    "id": "DEV-01",
    "group": "设备",
    "name": "连接戒指引导",
    "route": "`/device/connect`",
    "priority": "P0",
    "parent": "ONB-03 / 今日空状态 / DEV-10 / PERM-01 / 帮助",
    "function": "说明连接前准备；用户主动查找时检查蓝牙并交接扫描页，不在本页绑定",
    "layout": "准备连接标题、现有戒指图、放近/有电/蓝牙三条提示；单一查找按钮、就地连接帮助；只在异常时出现原因与恢复动作",
    "data": "connectionIntro.permission/returnRoute/request（ID、sourcePage、checking/complete/failed、readyAt、outcome）；toggles.bluetooth；现有同步、固件、测量和重置状态",
    "interaction": "首次点击开始查找先说明蓝牙用途；已就绪直接 DEV-02；未允许/蓝牙关闭可查看开启方法，失败可重新检查；帮助弹层可关闭或进入客服，返回继续原流程",
    "logic": "未知权限不推断蓝牙关闭；进入本页不自动请求或扫描；扫描交接不修改当前设备连接状态、不激活、不发成长或生成健康值；返回保存来源页，刷新或启动恢复继续同一请求；离页后结果仅保存、不强制跳页",
    "exception": "检查中禁重复操作；拒绝、蓝牙关闭、检查失败均可恢复，失败不覆盖许可；同步/更新/测量/重置未完成时阻止冲突扫描并说明原因；短屏可滚动，不隐藏必要动作",
    "ios": "正式实现使用系统许可与蓝牙状态回调；本地原型不调用系统设置或蓝牙 API",
    "android": "正式实现按平台权限与 SDK Adapter 合同检查；本地仅模拟，待真机逐项验收",
    "sdk": "docs/mobile/SDK_ADAPTER_CONTRACT.md：scan/connect/bind 分开；本页仅检查准备并导航，不调用 APP_BIND",
    "rules": "权限检查与设备连接状态分离；扫描不得覆盖正在进行的设备操作",
    "backend": "本轮不改真实接口、设备归属或同步游标",
    "owner": "产品+UI+SDK+双端",
    "source": "2026-09-07 用户逐页审阅；当前连接流程、SDK Adapter 合同与现有品牌素材",
    "note": "DEV-01 已获用户确认；桌面审阅区模拟四种检查结果，不出现在手机中；DEV-02 已进入本轮单页实施"
  },
  {
    "id": "DEV-02",
    "group": "设备",
    "name": "扫描与选择戒指",
    "route": "`/device/scan`",
    "priority": "P0",
    "parent": "DEV-01",
    "function": "查找附近戒指；用户明确选择并继续后，把同一设备交给 DEV-03 确认",
    "layout": "沿用 DEV-01 标题与主次按钮；扫描中以正式符号和非百分比等待反馈表示；找到后显示设备尾号、信号提示、单选状态及继续按钮；手机内不展示模拟控制或技术说明",
    "data": "deviceScan：version、status、request（id、startedAt、readyAt、outcome）、results、selectedId、handoff、finishedAt、reason；pairedDevice 仅在下一页明确配对确认后写入",
    "interaction": "从 DEV-01 开始查找进入等待；单枚也需明确选择；多枚不默认选最强信号；重新查找清除旧选择；停止/返回可取消；帮助关闭保留选择，蓝牙异常一键查看开启方法",
    "logic": "状态与实际已连接设备分离；查找和选择不绑定、不改会员资产或健康数据；按设备标识去重；无选择深链 DEV-03 回本页；结果与确认衔接同一尾号，配对后设备名称保持一致",
    "exception": "空/失败/弱信号/蓝牙关闭/权限撤回可恢复；操作冲突阻止扫描；刷新和重开恢复同一模拟请求，旧结果不续期；后台完成仅记录、不拉回；超时结果必须重查，不能直接配对",
    "ios": "真实蓝牙扫描及权限由适配器回调提供，应用恢复需重新确认外围设备可达性；不得把网页模拟计时当真机扫描",
    "android": "按 SDK Adapter 合同区分 scan/connect/bind，系统权限与设备去重由双端落实；真实扫描待接入",
    "sdk": "docs/mobile/SDK_ADAPTER_CONTRACT.md；本地模块 device-scan-page.js 只演示状态与选择，不调用 APP_BIND 或系统扫描",
    "rules": "用户主动选择；设备操作互斥；过期/撤权结果不得继续；不支持的硬件能力不展示",
    "backend": "本轮不改真实设备归属、账户资产、同步游标与接口",
    "owner": "产品+UI+SDK+双端",
    "source": "2026-09-07 用户逐页审阅；已确认 DEV-01 视觉与 SDK Adapter 合同",
    "note": "DEV-02 已获用户确认；1.6 秒扫描与 60 秒结果有效期仅为审阅参数，需真机验证确定；DEV-03 按获批方案单页实施，原型待用户复核"
  },
  {
    "id": "DEV-03",
    "group": "设备",
    "name": "首次绑定确认",
    "route": "`/device/bind` · 条件确认弹层",
    "priority": "P0",
    "parent": "DEV-02",
    "function": "核对选中戒指与当前账号；明确区分首次绑定和本人戒指重连",
    "layout": "沿用 DEV-01/02 标题、正式符号、尾号卡片和底部主次按钮；账号脱敏；初始不假示连接中；技术审阅控件在手机外",
    "data": "deviceBinding：目标快照、账号关联、检查 ID/有效时间、归属和清数据能力、操作 ID/结果/时间/确认/是否应用、查询状态；deviceBindings 保存本地模拟归属；pairedDevice 仅成功回调写入",
    "interaction": "确认绑定；需要清戒指旧数据时明确二次确认；本人已绑定走连接；其他账号占用仅重新选择/客服；处理中、成功继续、明确失败重新检查、未知结果查询；返回/稍后查看不撤销已发操作",
    "logic": "首次绑定不等于激活，不发成长/积分/徽章，不生成健康值；重连不重复绑定或清数据；操作幂等；后台完成不跳页；刷新/重开查询同一操作；我的/设备页可继续；固件、同步、测量、重置互斥",
    "exception": "检查失败、能力未知、过期、其他账号占用、明确失败、蓝牙中断、结果不确定；未知结果必须查询原操作，不直接重试绑定；不泄露其他账号信息",
    "ios": "真实 Framework 与能力回调待确认，不能直接照搬 Android 清数据分支；能力未知不允许提交",
    "android": "按当前 SDK Adapter 合同模拟首次 APP_BIND 清戒指旧数据、本人 APP_CONNECT 不清数据；真实 SDK 待接入",
    "sdk": "docs/mobile/SDK_ADAPTER_CONTRACT.md；device-bind-page.js 为本地模拟，不发真实配对/绑定/清除指令",
    "rules": "用户明确选择与确认；绑定结果和物理连接分别判断；不覆盖历史、合法资产或其他任务状态",
    "backend": "需确认权威设备归属校验、幂等键、超时结果查询接口及双端能力矩阵；本轮没有真实后端变更",
    "owner": "SDK+双端+后端",
    "source": "2026-09-07 用户批准 DEV-03 方案；《设计心理学》反馈/防错原则；SDK Adapter 合同",
    "note": "DEV-03 修改后原型已获用户确认；DEV-04 已按获批方案实施，待用户复核；650ms/1600ms/900ms 与 60 秒有效期均为审阅参数，不是实际 SDK 性能承诺"
  },
  {
    "id": "DEV-04",
    "group": "设备",
    "name": "佩戴引导",
    "route": "`/device/wearing-guide` · 帮助/保养弹层",
    "priority": "P0",
    "parent": "DEV-03 / 我的",
    "function": "提供简短佩戴提示；按首次设置/日常回看保持正确去向，不冒充佩戴检测",
    "layout": "沿用 DEV-01～03 字体、返回和底部按钮；官方手部佩戴场景图、两条14px短提示、佩戴与保养/帮助弹层；不显示固定连接状态",
    "data": "deviceWearGuide：版本、导览ID、模式、返回页、账号/设备关联、绑定操作ID、帮助返回、已查看/继续时间；每条导览历史保存自己的上下文副本",
    "interaction": "绑定结果进入显示继续设置→DEV-05；DEV-10等入口回看显示知道了→原入口；帮助/保养关闭恢复焦点；客服返回仍是本次导览；刷新/重开/浏览器前后退保留各自来源",
    "logic": "仅写导航上下文与埋点，不写已佩戴状态，不触发绑定、清数据、同步或激活，不改变健康记录/会员资产；来源未知安全默认只读回看；同账号成功绑定结果可回看，不因缺少旧扫描记录重新绑定",
    "exception": "断连、蓝牙关闭、未绑定仍可阅读；继续设置保留 DEV-05 既有门控；过期账号/设备关联不能复用设置来源；无关客服入口不能被旧导览劫持",
    "ios": "静态说明及导航；不调用未确认的佩戴检测能力",
    "android": "静态说明及导航；不调用未确认的佩戴检测能力",
    "sdk": "docs/mobile/SDK_ADAPTER_CONTRACT.md；无佩戴检测、连接、同步或绑定调用",
    "rules": "首次流程与日常回看分开；硬件事实未确认不写成用户操作规则",
    "backend": "无新增真实接口；deviceWearGuide 为本地导航状态",
    "owner": "产品+UI+双端；方向与实物图由硬件/工厂核对",
    "source": "2026-09-07 用户批准 DEV-04 审评方案；官方品牌模特.jpg；hardware/ring-v1.0/待确认问题清单_v0.8.md Q19",
    "note": "可交互原型已获用户确认；现有品牌照片只作佩戴场景，不证明推荐指位/传感器朝向；准确方向图仍待工厂/产品确认，不虚构标记"
  },
  {
    "id": "DEV-05",
    "group": "设备",
    "name": "首次同步进度",
    "route": "`/device/initial-sync`",
    "priority": "P0",
    "parent": "DEV-04；我的/DEV-10恢复入口",
    "function": "完成这枚戒指的首次同步与设置，按实际结果继续，不由按钮制造成功",
    "layout": "沿用已确认设备引导视觉；正式符号、单一状态标题、读取/保存/完成三阶段、结果对应主操作、稍后继续和同步帮助",
    "data": "initialDeviceSync.operations：账号/设备/绑定世代、操作ID、阶段请求ID/起止时间/结果/应用标志，readAt/syncedAt/activatedAt分开；本次来源viewSource、后续去向和帮助/权限返回上下文",
    "interaction": "就绪自动开始；失败只重试未完成阶段；断连重新连接；蓝牙/附近设备权限经PERM-01处理后返回；帮助就地弹层、客服往返；已完成后点击继续，首次去ONB-04，资料已处理回设备或原入口",
    "logic": "按账号+具体设备+boundAt核验回执；同步和激活分别幂等；空记录成功不造健康值，不清旧数据/资料/资产/偏好；第一次同步不要求预先激活；渠道申请与硬件独立，忽略历史渠道落点，不再从设备激活回跳渠道流程",
    "exception": "权限拒绝/关闭、断连、读取/保存/设置失败、网络不可用仅阻挡需联网的设置结果；固件/测量/重置/其他同步互斥；注销、换账号/设备/重新绑定阻断旧回调；损坏缓存转可恢复状态",
    "ios": "本地原型模拟；原生连接状态核验、后台恢复及SDK阶段回调待接入",
    "android": "本地原型模拟；不得以倒计时完成代替SDK成功回执",
    "sdk": "docs/mobile/SDK_ADAPTER_CONTRACT.md；SyncStage语义阶段，不伪造百分比；保存后断连不重读已读部分",
    "rules": "退出不等于解绑，不承诺原生后台一直同步；重开保留已确认步骤，不自动抢页；设备信息/设备页共用设备事实与互斥",
    "backend": "正式同步与设备激活回执需后端/双端确认；原型记录零条结果，不接云上传，不实现真实原始数据或游标存储",
    "owner": "产品+UI+SDK+双端+后端",
    "source": "2026-09-07 用户确认 DEV-05 五项方案；SDK适配契约；DEV-04已确认视觉",
    "note": "DEV-05 修改后原型已获用户确认；桌面外侧可选择各阶段失败/慢速，用户界面不出现审阅控制或内部规则"
  },
  {
    "id": "ONB-04",
    "group": "首次使用",
    "name": "基础信息",
    "route": "`/onboarding/basic-profile`",
    "priority": "P0 可稍后填写",
    "parent": "DEV-05",
    "function": "激活后记录出生日期（自动显示年龄）、身高和体重",
    "layout": "返回、基础信息标题、一句选填说明；三个带标签/单位的字段在独立滚动区域；底部固定保存/稍后与必要状态反馈",
    "data": "basicProfile v2：draft/base/touched、accountRef、legacyConflicts、status、returnRoute/afterRoute、scrollTop/savedAt；profile为正式保存值；年龄从出生日期计算，不另存",
    "interaction": "三项选填，有输入即可尝试保存；失焦/提交后校验；保存成功首次进入ONB-02，从个人资料续填则返回ACC-01；稍后/返回保留草稿，ACC-01有自然续填入口；刷新/重开恢复",
    "logic": "只写有效非空字段，空项不删除旧值；保留独立草稿与字段基线，未编辑项合并最新资料，冲突确认后保存；旧稿无基线则保守确认；不增加设备写入/健康结论/会员奖励",
    "exception": "未来/无效日期、范围错误、原始数字输入、输入法组合、旧稿冲突、写入失败可重试；失败退出需确认且不承诺重开仍有未持久化内容；账号变化不显示/提交旧稿，仍能离开；短屏和视口收缩",
    "ios": "沿用现有表单与系统日期选择能力，待原生实现",
    "android": "沿用现有表单与系统日期选择能力，待原生实现",
    "sdk": "本页无设备写入",
    "rules": "用户填写与设备数据分开；保存前只作为草稿；填写不生成健康值或奖励",
    "backend": "本地写入成功才更新正式profile并成功跳页；正式资料服务、账号隔离、服务端版本冲突和真机键盘待联调，不用模拟延迟冒充接口",
    "owner": "产品+UI+双端+后端",
    "source": "2026-09-07 用户确认 ONB-04 六项修改方案；DEV-05 原型已确认",
    "note": "用户已确认原型，进入ONB-02逐页审评；只补ACC-01续填入口，不重做其余个人资料；不展示后台状态/昵称营销/生日权益设置"
  },
  {
    "id": "RHY-00",
    "group": "节律",
    "name": "节律基础设置",
    "route": "`/rhythm/setup`",
    "priority": "P0 可跳过",
    "parent": "RHY-01也想看看预计经期／日期核对入口",
    "function": "自愿选择只记录感受或经期记录与预测，核对后保存",
    "layout": "两种记录方式；周期选择后展开三项字段及预测开关；固定保存与稍后设置；提醒仍在RHY-04",
    "data": "复用rhythmSettingsEditor账号saved/draft/base、rhythmSettings及现有prediction；pageViews.RHY-00按账号保存位置与折叠",
    "interaction": "输入先保留草稿，显式保存后回RHY-01；稍后／返回不改变正式设置；失败留页重试；放弃二次确认；已记录开始日只读并回经期记录修改",
    "logic": "不要求设备或周期日期即可记录感受；切换记录方式保留合法历史；不自动恢复暂停、不重造删除数据、不凭参数补出真实结束日期",
    "exception": "字段缺失／越界／未来／小数、草稿冲突、存储失败、已删除、跨账号、注销／健康删除中均有守卫与恢复路径",
    "ios": "本地原型已验证；原生键盘、日期控件、读屏与进程恢复待真机验收",
    "android": "本地原型已验证；原生键盘、日期控件、读屏与进程恢复待真机验收",
    "sdk": "无新增SDK依赖；仅用户自愿输入",
    "rules": "20–45／2–10沿用既有填写范围，不作为医学正常标准；预测不能确认排卵或用于避孕",
    "backend": "真实账号鉴权、版本冲突、原子保存及跨设备一致性待对接；本机草稿不等于云端保存",
    "owner": "产品+双端+后端",
    "source": "本目录README／rhythm-setup-page.js／rhythm-settings-store.js",
    "note": "2026-09-08用户已确认，5.2→8.8启发式自评，25组本页与3组入口回归通过；接续TOD-04旧入口兼容收口，仅本地、不Git／上线／打包。稍后设置不再强制切为只记录模式。"
  },
  {
    "id": "ONB-02",
    "group": "首次使用",
    "name": "身体天气建立中",
    "route": "`/today?state=building`",
    "priority": "P0 状态",
    "parent": "ONB-04 / 首次使用状态恢复",
    "function": "首次连接后说明身体天气如何开始；无需等待，可直接进入今日",
    "layout": "返回、正式符号、单句状态、三个使用步骤图标、折叠说明；底部固定进入今日与条件化帮助",
    "data": "只读membershipHardwareState/dataLifecycle/deviceStatus/bluetooth；复用bodyWeatherPageState().ready核对记录日期；不新增健康值、进度、持久字段或事件",
    "interaction": "ONB-04进入；主操作到TOD-01；佩戴指南直达DEV-04并返回本页；异常到DEV-10，未绑定到DEV-01；展开说明；刷新/返回沿用导航恢复",
    "logic": "按真实阶段显示；旧日期不说今天已更新；断连不清已有阶段；去掉固定3/7天和后台轨道；浏览本页不生成数据或完成状态",
    "exception": "未绑定、解绑保留、待激活、无记录、积累、旧日期、缺口、未知阶段、蓝牙关闭/断连/同步中/低电量；始终可进入今日",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07按原快照→建议自审迭代→实施流程完成；启发式评分5.2→9.2，8组局部验证通过，用户已确认。本页刷新后返回优先真实来源，无来源返回今日；不改共享规则"
  },
  {
    "id": "TOD-01",
    "group": "今日",
    "name": "今日首页",
    "route": "`/today`",
    "priority": "P0",
    "parent": "Tab",
    "function": "一眼看懂今天如何安排",
    "layout": "大状态主视觉、三信号与健康入口、一主行动、条件出现的Studio次日提醒、用户记录、折叠灵感、夜间内容、Select/Studio 双卡",
    "data": "状态名、一句结论与依据、三信号、deviceLastSyncedAt、当天用户记录、nightChoice/nightSession；昨天完成的同账号Studio记录、固定日期回顾与分场次已读状态",
    "interaction": "有数据时卡片看原因、主按钮定位建议；首次无数据卡片直达ONB-02并返回，正常主按钮浏览睡前内容或继续原会话，需处理设备时到DEV-10；未绑定保留连接；记录/灵感/夜间/服务入口与恢复不变",
    "logic": "早晨主状态稳定；首页不显示总分和原始指标墙；Studio次日提醒不等于健康报告已齐全，完整/进度/基础参与分别直达06/12/15，成功进入后按内容版本已读，仍保留原预约入口",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "保留已确认的第一、第二优先及原布局。2026-09-07首次无数据专项：设备同步与身体记录分开说明，不承诺一晚必出结果；未绑定/解绑保留独立文案；同日稳定轮换；首屏主操作按设备状态与会话选择。9组局部验证通过，专家评分7.2→8.9，待用户确认；未上线/打包"
  },
  {
    "id": "TOD-02",
    "group": "今日",
    "name": "记下此刻感受",
    "route": "/today/record（独立填写页）",
    "priority": "P1",
    "parent": "TOD-01",
    "function": "可选标签或文字记录感受；查看、修改和单条删除已保存记录",
    "layout": "顶部返回与帮助；一排五项天气图标+感受短标签，选中描边/底色/勾选；折叠的情况选填；文字选填；底部一个保存按钮；无一级导航",
    "data": "用户记录 id/labels/original/source/occurredAt/updatedAt；recordDraft 与 recordEditDraft 分离；recordEditorMode",
    "interaction": "多选、纯文字或纯标签保存；空白禁用；返回/刷新续写；详情修改；单条删除二次确认",
    "logic": "不改写设备值；旧标签原样保留；修改保留原 ID/发生日期/来源，仅更新内容与 updatedAt，不重复奖励",
    "exception": "无设备/无健康数据也可记录；存储失败保留内容并重试；记录不存在不补建；编辑草稿可确认放弃",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无需设备数据；原型使用独立用户记录存储",
    "rules": "用户记录与设备及 AI 数据分离；明确保存、单条删除与草稿保护",
    "backend": "正式接入用户记录 CRUD、版本校验与失败回执",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08按用户要求将五项感受改为天气图标选择：晴天/晴间多云/阴天/风/小雨分别辅助原有有精神/还好/有点累/紧绷/低落。名称、可多选、草稿与保存值不变；情况选填、活动单选与旧标签不套天气映射。天气仅为主观感受图示，不是设备Body Weather或健康分数。本轮本地待确认。"
  },
  {
    "id": "TOD-03",
    "group": "今日",
    "name": "身体天气详情",
    "route": "`/today/body-weather`",
    "priority": "P0",
    "parent": "TOD-01",
    "function": "看清记录日期、身体天气和下一步；按同一天查看睡眠/身体能量/活动；表达不同感受",
    "layout": "日期、30px状态名与16px说明、纠正与行动、三项记录、同页分类趋势图及区间分布、固定最近7天卡片、感受记录和说明",
    "data": "healthDemoRecordDate 与 healthDetailContext；同源睡眠阶段；aiCorrectionDraft/History与解释关联；recordDraft.returnRoute；bodyWeatherTrendView周期/日期/owner；history.state.bodyWeatherContext按访问保存区间/日期/记录显隐/滚动；30日显式原型fixture",
    "interaction": "详情同日往返；纠正/撤销；趋势图7/14/30切换，点图/日期选择/前后一天；卡片始终最近7天；记录标记显隐；刷新恢复与边界焦点；感受保存回原区间；夜间/Halo/分享",
    "logic": "反馈与设备事实分开；仅当天同一解释的有效纠正影响本次表达；取消不覆盖已存反馈，旧反馈保留历史；分享不默认带自由文字",
    "exception": "无数据三槽空态；部分数据保留已同步片段；旧记录不充当今天；记录不足不生成比较或趋势；存储失败保留原值和草稿",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "用户已确认同页曲线、固定最近7天卡片及字号。2026-09-08追加旧TOD-04链接兼容，定位本页完整趋势，保留已有区间/日期；30天区间回顾保留健康报告入口。曲线与分布同源，不画装饰分数；无可解释数据仍空态。TOD-04兼容本轮待确认，TOD-01布局不改。"
  },
  {
    "id": "TOD-04",
    "group": "今日",
    "name": "状态趋势（旧链接兼容）",
    "route": "`/today/body-weather/trend`",
    "priority": "兼容入口，不独立展示",
    "parent": "TOD-03",
    "function": "旧书签与遗留入口转入TOD-03同页完整状态趋势",
    "layout": "无独立页面；复用TOD-03曲线、7/14/30区间分布和最近7天卡片",
    "data": "旧trendPeriod仅作无有效新选择时的迁移后备；bodyWeatherTrendView；history.state.bodyWeatherContext；复用pageViews及现有同源数据",
    "interaction": "旧链接定位趋势区；前进/返回恢复各次区间、日期、记录显隐及位置；30天回顾可打开TOD-09报告",
    "logic": "先执行登录与注销门禁再转向；新日期选择优先；旧路由退出目录与逐页箭头；已映射的相邻历史不会困住返回",
    "exception": "非法/未来/区间外日期归一到有效日期；未绑定/解绑/不足/过期仍空态；写入失败不写健康或用户记录",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08本地兼容修改后待确认；4.8→8.8启发式自评，18组兼容与11组原曲线交互回归通过。TOD-04 ID只作旧链接别名，不代表新增页面或健康算法；生产深链映射仍需双端接入。"
  },
  {
    "id": "TOD-05",
    "group": "今日",
    "name": "睡眠详情",
    "route": "`/today/sleep`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-03 / TOD-08",
    "function": "查看所选醒来日期的睡眠记录与阶段，按需了解估算边界",
    "layout": "日期、总睡眠、入睡与醒来、可选阶段图与时段列表、科普/来源折叠、夜间与目标入口",
    "data": "固定日期的单晚演示：总睡眠402分，清醒34分，00:02–07:18；浅睡232/深睡74/REM96；图、总量、分段时长由同一数组生成；沿用healthDetailContext，新增sleepStage仅保存界面筛选",
    "interaction": "日期前后/日历、点选阶段及查看全部、说明展开/收起、返回健康数据保留日期；进入夜间或睡眠目标，系统返回恢复详情",
    "logic": "有效原始记录不受7天基线门槛限制；无数据或未绑定无数值与图，02:10–03:00缺失不展示整晚汇总；历史未知日期为空，不生成多晚趋势；阶段仅为估算，不按单项判定睡眠好坏",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认本页，接续单页审阅TOD-06；不改夜间页。去除无历史依据的趋势与86%睡眠效率示例；现有用户记录和业务数据保留"
  },
  {
    "id": "TOD-06",
    "group": "今日",
    "name": "身体能量详情",
    "route": "`/today/energy`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-03 / TOD-08",
    "function": "看懂所选日期的身体状态、参考记录和HRV含义；需要时记录自己的感受",
    "layout": "日期、状态与一句建议、HRV/静息心率/睡眠证据面板、HRV科普与来源折叠、用户感受、夜间入口；无分数与装饰趋势",
    "data": "沿用healthDetailContext/healthSelectedDate和固定healthDemoRecordDate；单晚示例HRV42ms、静息心率58次/分；睡眠复用TOD-05同一段数组（402分）；recordDraft/userRecords独立保存；不新增健康量化字段",
    "interaction": "切换日期；睡眠行进入同日TOD-05；HRV入口直接展开说明；感受可保存/查看原记录、刷新续填；返回原入口日期，前进恢复详情日期；去夜间不自动播放",
    "logic": "有完整原始记录即可显示读数，个人范围未建立不判断高低；缺失/未绑定/未知日期无个人数值与趋势；只有可解释状态显示分类比较，不画精确位置与阈值；手动记录不改变健康状态、成长或积分。生产仍需明确指标、窗口、筛选、汇总与算法版本，只与同算法同场景历史比较",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认本页，接续TOD-07活动详情。用户侧保留通俗数值含义、自主神经与适用边界，不展示公式/算法；删除无依据的多晚趋势、91%覆盖率和少睡36分示例。R01光学估算不是ECG测量；协议单值只写HRV(ms)，未定义RMSSD/SDNN，Donni API未获生产放行，正式口径仍需算法/供应商确认"
  },
  {
    "id": "TOD-07",
    "group": "今日",
    "name": "活动详情",
    "route": "`/today/activity-fit`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-01 / TOD-03 / TOD-08",
    "function": "查看所选日期已同步活动记录，按需记录活动感受、查看同日身体状态",
    "layout": "日期、已同步步数、同步入口、活动消耗估算；活动感受区独立记录此刻/查看记录，当日/全部筛选；身体能量入口，最后数据来源折叠。不放未验证趋势、默认目标或强度处方",
    "data": "单日示例4862步/284千卡保留；activityRecordDraft与通用草稿隔离，subjectiveRecords按category=activity筛选；activityRecordsScope、pageViews.activitySections记录界面状态，recordEditDraft.returnContext保存来源日期/展开/滚动/筛选；activitySync.blocked区分受阻与成功，不新增健康计量或奖励字段",
    "interaction": "轻松/刚刚好/有点累在新增与编辑均单选，也可纯文字；显式保存后打开记录回看，历史页新增仍记今天且不切换浏览日期；编辑保存/返回/放弃/刷新续写保留原记录时间和来源页日期位置；同步网络重试、蓝牙权限和设备断连入口按原因区分；同日TOD-06返回",
    "logic": "原始活动记录不等待基线；夜间缺口不隐藏活动片段，无数据不显示数值或填0；同步模拟不新增步数、不修补缺口/基线；活动记录仅按明确category筛选，不迁移旧记录或共享草稿；感受使用保存时刻，与所浏览健康日期无关，不发奖励",
    "exception": "建立中、部分数据、无数据、未连接；存储失败保留草稿；断网恢复后可重试，蓝牙关闭引导权限，戒指断连引导设备连接；同步失败不更新旧值和回执",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认四项修订后的本地原型，接续HLT-01原页审评。当前示例只列Halo Ring来源，不假称手机已去重；删除46/14/4分钟强度分布、久坐1次、89%完整率、5/7进度与无依据7日趋势。生产累计upsert/多源去重及消耗指标需SDK和后端验证，当前未接真实数据"
  },
  {
    "id": "TOD-08",
    "group": "今日",
    "name": "收听回顾",
    "route": "`/today/last-night`",
    "priority": "P0",
    "parent": "TOD-01",
    "function": "回看指定的一次收听，记录个人感受；不替代睡眠摘要",
    "layout": "内容与实际日期/已听时长、练习确认（仅引导类）、感受、折叠选填补充、保存状态",
    "data": "nightHistory按session_id保存；nightReviewDrafts按session_id隔离草稿；nightReviewEntry保存真实入口",
    "interaction": "选择感受（含暂时说不清）、保存、修改、取消修改、保留草稿返回；刷新继续",
    "logic": "主观记录不改设备数据；独立草稿，写入成功才提交；取消不改原记录；不同内容不累计观察次数",
    "exception": "无历史、记录不存在、时间/时长未知、存储失败保留当前输入并重试；未绑定可记录公开内容",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认修订后的原型，接续TOD-09原页审评。保留TOD-08 ID及旧route兼容；TOD-09查看播放记录→NIG-10，不把历史选中项称昨晚。仅本地原型保存，真实账号隔离/后端同步仍需联调。"
  },
  {
    "id": "TOD-09",
    "group": "今日",
    "name": "健康报告",
    "route": "`/reports/14-nights`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-03（30天区间回顾）",
    "function": "查看14个有效夜晚的积累、生成状态与已保存报告；历史报告独立于当前连接状态",
    "layout": "首份14晚报告进度、我的报告；页内切换记录情况/具体报告详情",
    "data": "healthReports.accounts按账号上下文隔离；ledger含ruleVersion/date/status/postedAt；request冻结14晚；reports含id/type/range/generatedAt/ruleVersion/nights；healthReportsDemo独立演示",
    "interaction": "查看计入/未计入夜晚；模拟生成/失败重试/离线恢复；按报告ID查看；返回列表/原入口及滚动位置",
    "logic": "有效夜不从BodyWeather阶段推算；同日期按最新回执去重；写入成功才显示报告，重试不重复生成或覆盖旧快照；月报只展示已生成回执，不自定门槛",
    "exception": "无已核验记录不造进度/健康值；生成或存储失败；离线、退出恢复；无效报告ID；解绑/近期质量受限仍保留历史入口；健康删除处理中拦截报告内容",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认修订后的原型，接续TOD-10。保留TOD-09 ID/旧route；新health-reports-page模块。1.8秒生成仅隔离演示，真实规则服务/生成服务/月报周期与最低覆盖条件待确认。旧TOD-04月报固定内容改为本页入口。"
  },
  {
    "id": "TOD-10",
    "group": "今日",
    "name": "分享身体天气",
    "route": "`/share/body-weather`",
    "priority": "P1",
    "parent": "TOD-03 分享这次状态；兼容旧TOD-09入口",
    "function": "将这次已可解释的身体天气制作成分享卡，确认内容后再交给系统分享或下载",
    "layout": "日期、原尺寸预览、三种背景；编辑底部固定继续；同页确认预览及分享/保存/复制",
    "data": "shareEditors.accounts按模拟账号隔离；source仅key/date/title/description；background/zoom/photoSelected/entry/panel/depth/tops；照片、解码对象、PNG仅内存",
    "interaction": "背景即时预览；相册选择/更换/移除、只缩放照片；确认预览后系统分享、下载或复制；取消/失败保留编辑；恢复来源与位置",
    "logic": "缺数/过期/未绑定/删除处理中不生成卡片；导出/复制与确认预览同一快照；源变化失效需重新预览；不发健康原始值、用户原文；相册不上传、不默认持久化；系统成功不等于收件人收到",
    "exception": "坏图/大图/解码失败、PNG空或异常、canShare不支持/throw、分享取消/失败、剪贴板拒绝、本地保存失败、刷新照片重选、跨账号与返回",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认修改后原型（5.0→8.8分），接续TOD-11。仅本地，未外发。保留正式符号；不增一级入口、医学算法或分享奖励；未接真实移动端分享/相册。"
  },
  {
    "id": "TOD-11",
    "group": "今日",
    "name": "数据来源与质量说明",
    "route": "`/today/data-quality`（保留 TOD-11）",
    "priority": "P0",
    "parent": "TOD-01 记录进度；TOD-03 数据来源；HLT-00 数据说明",
    "function": "按所选日期查看可用记录、来源与当前戒指同步情况",
    "layout": "日期与状态、首屏连接入口、睡眠/HRV/活动、折叠更多指标、设备状态与同步回执、用户记录、质量说明",
    "data": "dataQualityView：owner/date/entry/entryDate/entryContext/top/sections/trip；逐指标复用 healthOverviewReading 可用性；读取同账号当前设备 deviceHub facts/lastResult；subjectiveRecords 按北京时间日期计数",
    "interaction": "7指标保留日期往返；展开来源；进入 DEV-10 后由用户启动已有同步流程；刷新、设备返回与浏览器前后恢复日期/入口/展开/滚动；本地保存失败就地重试",
    "logic": "不生成健康数值/覆盖率/有效夜晚计数，不替同步成功补出健康数据；采集日期/个人范围/连接状态分开；无记录/未绑定/历史/删除处理都有真实降级；未知来源不声称已读取或去重",
    "exception": "同账号当前设备回执校验；忽略其他账号/设备/未来/绑定前时间；未绑定不宣称历史删除；健康删除期间隐藏指标与用户记录计数；同步失败由设备页重试",
    "ios": "待双端接入真实数据回执并逐项验收",
    "android": "待双端接入真实数据回执并逐项验收",
    "sdk": "沿用 DEV-10 同步状态机；原型不调用真实硬件",
    "rules": "记录可用性与可解释程度分开；无数据不显示值或趋势",
    "backend": "待接入逐项来源/覆盖回执及服务端删除状态；不猜测缺失原因",
    "owner": "产品+算法+双端",
    "source": "本目录 README / data-quality-page.js",
    "note": "2026-09-07用户已确认修改后原型（4.8→8.8分），要求后续加速并保留逐页确认。改为现有页面体系内的独立详情，纠正旧Bottom Sheet元数据。保留所有已确认页面与并行改动；未上线、提交或打包。"
  },
  {
    "id": "HLT-00",
    "name": "健康数据",
    "route": "`/health`",
    "priority": "P0",
    "parent": "TOD-01 → 健康数据",
    "note": "逐页审阅版：固定八项记录入口；当前仅有一个固定日期的演示快照，其他日期为空，不伪造历史。未重做既有详情。",
    "group": "健康数据",
    "function": "区分测量记录可用性与个人解释条件",
    "layout": "日期与同步、Body Weather 当前累计建立进度、主要记录（睡眠/身体能量/活动）、生理指标（心率/HRV/呼吸率/血氧/皮肤温度）、测量与报告",
    "data": "healthSelectedDate、healthDemoRecordDate、healthDetailContext；Body Weather 7 天建立进度与 14 晚报告分开；沿用生命周期演示计数，不随浏览日期改变；八项固定入口，未连接不展示健康值",
    "interaction": "展开/收起建立说明及连接/查看 Body Weather；前后日期/日历/回今天、进入指标详情并保留日期与返回位置；HRV 定位既有能量页的 HRV 区域；历史空日期详情不渲染当日示例数据",
    "logic": "有记录但基线不足时展示已同步数值，暂不比较个人范围；缺失时不复用完整整晚汇总或把缺失当作身体异常",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-01",
    "name": "心率",
    "route": "`/health/heart-rate`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-06",
    "note": "2026-09-07 当日趋势原型 heart-trend 已获用户确认，进入 HLT-02 原页审评。最新值与曲线共用示例记录，点选与最新值分开，缺口不补线。",
    "group": "健康数据",
    "function": "查看所选日期最近心率和静息摘要，分清采集时间与同步时间；查看或补充独立的用户感受记录。",
    "layout": "日期栏 → 最近一次读数/采集时间 → 当日心率变化与独立选中读数 → 静息摘要 → 感受入口与历史折叠 → 来源说明。",
    "data": "heart-trend.js 提供固定示例日期的 29 条采样、4 个明确连续片段、occurredAt/time/minute/value/segment/resting；最近读数为最后一个有效采样 72@08:38，示例静息标签汇总为日间61/夜间58；limited仅1点。heartTrendSelection={date,minute}及返回上下文保存选择，未接真实SDK。",
    "interaction": "日期切换；曲线点按/横拖、上一条/下一条/最近、键盘方向键与Home/End；纵向滚动不被劫持；缺口显示暂无记录。记录与DEV-10同步原路返回并恢复日期、图中选择、展开和位置，刷新重开可续。",
    "logic": "图表、最近读数与摘要来自同一示例模型，明确标注示例数据；只有同segment连接，单点不连线，未来采样过滤，无数据不画；不加医学正常区间或7/30天假趋势。静息标签和均值仅用于示例一致性，不是生产SDK算法。Body Weather不门控原始采样。",
    "exception": "未绑定、无数据、历史缺失、夜间记录不完整；DEV-10 承接同步失败/权限/连接恢复；记录草稿与日期上下文支持刷新重开，旧月度草稿不被覆盖。",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-02",
    "name": "夜间呼吸率",
    "route": "`/health/respiration`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-05",
    "note": "2026-09-07 用户已确认 respiration-approved 原型；健康数据逐页审评继续 HLT-05。",
    "group": "健康数据",
    "function": "按醒来日期查看夜间平均呼吸率、近7晚变化及同一晚睡眠；感受记录单独保存和回看。",
    "layout": "日期→夜间平均与所属晚间→近7晚可点选趋势→同晚睡眠→折叠解释→用户记录与来源；无Body Weather进度大卡。",
    "data": "respiration-trend.js 单源固定示例：healthDemoRecordDate前6日至当日的date/value，含1晚空缺；窗口days与selected同源，source/version/latest；按UTC+8醒来日期及08:44示例可用时刻过滤。",
    "interaction": "日期前后/日历/今天/最近；点按、横拖松手或键盘/44px步进选晚，日期与读数同步；刷新保留窗口；同晚TOD-05、TOD-02记录及DEV-10同步后原路返回。",
    "logic": "只展示已存在的夜间平均；缺口不补线不算零，单点不连线，无个人范围/覆盖率/健康判断。原始读数不等待Body Weather；记录按真实保存时间归档，不倒填所选夜晚。",
    "exception": "未绑定/none无健康数值及趋势；limited不估算整晚；选中空缺仍可查看已有其他夜晚。存储失败留在编辑器并保留草稿，提醒先不要关闭；同步成功不凭空生成数据。",
    "sdk": "原型未接真实呼吸率数据；正式夜间平均、有效性、归档日期须接SDK/后端确认字段。",
    "rules": "醒来日期与睡眠一致；7日槽位固定，窗口/选中独立；不设置医学正常色带或会员门槛。",
    "backend": "respirationWindowEnd、respirationSleepReturn及既有健康/记录/设备返回上下文仅为本地原型状态；无新增后端业务规则或奖励埋点。",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-03",
    "name": "主动测量中心与历史",
    "route": "`/health/measure`",
    "priority": "P0",
    "parent": "HLT-00",
    "note": "2026-09-07 用户已确认measurement-center，独立审评4→9/10；接续HLT04过程与结果页。",
    "group": "健康数据",
    "function": "判断可用测量、恢复未完成血氧请求，按类型回看当前账号已保存结果。心率/HRV提供能力说明，温度查看夜间记录，不冒充即时测温。",
    "layout": "短标题与帮助→可点的连接状态→运行/失败/待保存恢复→开始/说明/查看三项→分类型日期历史与分页→折叠帮助。",
    "data": "中心/导出/隐私计数共用allMeasurementRecords；显式owner归属、有效非未来时间与质量过滤，按记录value/metrics呈现。旧lastMeasurement原始对象不改动、不擅自认领。",
    "interaction": "血氧沿用HLT04完整请求；恢复不会重复新建，待保存继续同一结果。全部/心率/血氧/温度真实筛选，5条起分页；记录弹层可查看当日血氧，返回恢复筛选与位置。",
    "logic": "血氧未知/不支持/未绑定/断连/设备忙不能开始；绑定不影响已有归属记录查看。心率与温度旧新启动及HLT04非血氧深链拦截，历史仍保留可读，不以接口名承诺量产能力。",
    "exception": "运行/失败/待保存分开恢复，不新增失败数值；数据处理中不显示记录或开始入口；无owner/其他账号旧值不展示导出、不随当前账号测量删除而清除。",
    "sdk": "复用现有氧测量原型模型，量产能力、测量时长和质量判定待硬件/后端确认；未接真实设备，不新增阈值。",
    "rules": "主动结果不计入睡眠汇总；夜间温度查看与即时测温分开。未增加会员限制、奖励或新一级入口。",
    "backend": "新增measurementCenterFilter/measurementHistoryLimit本地持久化；复用oxygenMeasurements与页面视图。历史查看单独push路由，原HLT04测量回跳逻辑保留。",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-04",
    "name": "主动测量过程与结果",
    "route": "`/health/measure/:type`",
    "priority": "P0",
    "parent": "HLT-03",
    "note": "2026-09-07 用户已确认 measurement-process，独立静态/快照审评7.2→9.1/10。只完善血氧流程，未开放能力待确认的心率/温度新测量。",
    "group": "健康数据",
    "function": "看清进行中、失败、待保存、已完成；区分保留这次测量与终止，完成后查看同一次血氧记录。",
    "layout": "固定血氧测量标题/返回/演示标记→测量/结果/保存三步离散状态→状态/正式超级符号或读数→原因旁恢复入口→主要操作→折叠说明。",
    "data": "沿用oxygenMeasurements.accounts[owner].request/records；requestId、pendingResult、原始数值与采集时间不变，页面只从当前账号同一请求派生。",
    "interaction": "稍后继续保留请求，取消结束本次；待保存放弃需二次确认且可反悔；重试保存不重采样；查看血氧记录返回HLT05对应记录，普通返回按HLT03/HLT05来源恢复。",
    "logic": "不造倒计时或百分比；三步仅表达已完成事实。discardIntent只在内存绑定owner/id，确认需当前HLT04、当前请求与仍存在的对应弹窗；关闭、换号或换请求后旧确认无效。",
    "exception": "存储失败不显示已保存，重试保留同次结果；取消写入失败不清空请求；已获取结果保存不要求BLE，解绑后可保存本人已获结果。缺失完成记录不造值。",
    "sdk": "仅演示UI与本地请求生命周期，真实采集能力/时长/精度/质量待硬件及后端联调。",
    "rules": "原型数据非真实采集；主动血氧不加入睡眠平均、不改变会员权益与Body Weather规则。",
    "backend": "无新增后端字段、账本或外发埋点；新增临时discardIntent及页面恢复/确认回调，HLT04深链以权威本地请求而非缓存flags判断可达。",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-05",
    "name": "血氧",
    "route": "`/health/spo2`",
    "priority": "P0 Gated",
    "parent": "HLT-00",
    "note": "2026-09-07 用户已确认 oxygen-curve：当日采用点状图+自动记录曲线，撤回柱图，旧快照保留。主动测量仍复用HLT-04，不新增一级入口。",
    "group": "健康数据",
    "function": "按采集日期查看白天/夜间的具体血氧记录，查看当日最近读数与来源；睡眠平均单独切换，主动测量完成后定位具体记录。",
    "layout": "日期→当日/睡眠切换→最近读数与测量入口并排→当日点状图+曲线/记录列表，或夜间均值/近7晚图→帮助、解释、感受记录与来源。",
    "data": "oxygen-day.js: id/value/occurredAt/time/minute/kind，按UTC+8采集日期归档，HLT-00同源latest；oxygen-trend.js独立夜间平均按醒来日期归档。两个图互斥，自动示例不代表连续采样。",
    "interaction": "点按/横拖/键盘/44px按钮查具体记录；日期/模式/选择刷新重开保留；主动测量→HLT04→固定请求结果落盘→查看这次记录定位实际日期id，取消/失败返回原上下文。",
    "logic": "当日最近一次不随图中选择改变；每点一条记录，实心自动/空心菱形主动。仅自动点间平滑连线，不超出相邻值、不外推、不补新读数；不足2点无曲线，主动点不入线。常规90–100%刻度，低值自动扩轴，不画正常带。单次测量不混入睡眠平均。能力unknown/unsupported不伪造值或放行新测量；采集时逐次检查账号、绑定、蓝牙和互斥。",
    "exception": "none不造自动数据，已保存的有效主动记录可独立查看；off/quality不抹掉主动结果。存储失败保留同一pendingResult，重试不新造时间或重复入账；已采得结果本地保存不再要求蓝牙。账号切换/取消晚到不混入新账号。",
    "sdk": "SDK列有历史与主动血氧接口；量产设备采样频率、自动/主动能力与质量、睡眠聚合及后端字段待确认，未承诺全天连续监测、临床精度或真实设备采集。",
    "rules": "当日记录按采集日期，夜间均值按醒来日期；症状优先。审阅场景非用户硬件设置；当前原型的可用示例不等于实际能力回执。",
    "backend": "新增oxygenMode/oxygenDaySelection、oxygenMeasurements.accounts[owner].records/request；requestId幂等及pendingResult持久化，保留旧lastMeasurement。SET01导出删除同源且保护其他账号记录。无新会员规则/奖励或外发埋点。",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-06",
    "name": "皮肤温度状态与趋势",
    "route": "`/health/temperature`",
    "priority": "P0 Gated",
    "parent": "HLT-00",
    "note": "2026-09-07 用户已确认temperature-arrow（含睡眠入口18px箭头修复）；独立启发式审评5.4→8.8/10。接续HLT03，夜间温度与主动测温分开。",
    "group": "健康数据",
    "function": "按醒来日期查看夜间皮肤温度相对个人平时的变化，理解正负及零值；需要时查看同晚睡眠、连接同步或记录感受。",
    "layout": "日期→相对变化主值/真实空态→近7晚点状曲线→同晚睡眠→折叠解释与不适帮助→感受记录→数据来源。",
    "data": "temperature-trend.js 同源模型：date/value/reason/recordDate/windowEnd。示例按UTC+8醒来日期，健康中心与详情同值；个人基线未建立不显示相对值。",
    "interaction": "点按、横拖、键盘及前后按钮查7晚；日期选择拒绝未来、缺数可回最近记录。查看睡眠/设备及新建或修改感受后返回原日期/趋势窗口，刷新恢复。",
    "logic": "±℃表示相对个人基线而非体温；0参考线不是正常区间。缺失断线不填0，单点无曲线，曲线不超出相邻值。只提供真实7晚示例，不保留虚假14/30天切换。",
    "exception": "未绑定、能力待确认、不支持、无记录、质量不足、个人基线建立中分别显示；质量不足保留其他历史；数据删除/注销处理中不显示健康值或记录入口。",
    "sdk": "SDK存在READ_TEMP和历史接口；量产支持、夜间聚合、精度、有效质量和个人基线算法待硬件/后端确认，本页不承诺即时测温。",
    "rules": "温度基线独立于Body Weather进度，不套用7晚门槛；相对值不能判定发热或疾病。示例状态切换只供审阅，不是用户配置硬件能力。",
    "backend": "持久化temperatureWindowEnd/temperatureReviewScenario/temperatureDemoEntry/temperatureExternalReturn，复用healthDetailContext与记录草稿。无新会员规则、成长奖励或外发埋点。",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "NIG-01",
    "group": "夜间",
    "name": "今晚首页",
    "route": "`/night`",
    "priority": "P0",
    "parent": "Tab",
    "function": "查看AI推荐组合、自己搭配内容、继续当前组合；首屏可见明早唤醒",
    "layout": "顶部夜间/历史→明早唤醒→当前会话（若有）→AI组合意图/推荐/逐段详情/选用→待播组合/总时长/开始/自己搭配→渐弱设置",
    "data": "nightPlan独立待播队列，nightRecommendationGoal只改预览；nightSession.tracks冻结本次顺序/内容/时长；wakeSettings已存值和wakeDraft草稿分开",
    "interaction": "显式选用推荐后定位待播组合不自动播放；逐段进入NIG02；NIG03增删、NIG05排序；顶部通常直达NIG06，有有效稍后提醒时优先显示提醒时间并直达NIG08，到期原位更新；草稿提示含稍后时长；当前会话优先续播",
    "logic": "AI为明确标识的本地推荐效果演示，不调用外部模型/不编健康依据。未绑定公共5/10/15分钟可组合，不附加尾段或奖励；正在播不受下次编辑影响",
    "exception": "空队列禁用开始；开始/暂停/归档写入失败保持原状态并可重试。到期不重新计时；通知关闭/草稿未保存明确提示",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "选择、播放、渐弱、唤醒和历史独立；后台会员规则不铺在前端首屏",
    "backend": "新增本地nightPlan/nightRecommendationGoal/nightContentDetail及history context；session新增tracks/planMode/recommendationId/ownerAccount/skipped/stopReason；night_plan_changed为本地事件，开始/完成增加content_ids/duration/stop_reason，无外发数据",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07 用户已确认 night-combo 夜间首页；依新增要求扩展既有NIG02/03/04/05/10，不增一级入口。上一版8.8→本轮独立9.1/10；22模型+12主流程+6独立组通过。后续按页逐个确认。"
  },
  {
    "id": "NIG-02",
    "group": "夜间",
    "name": "内容详情",
    "route": "`/night/content/:id`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-03 / NIG-04 / NIG-05 / NIG-10",
    "function": "逐段了解内容，再决定是否加入组合",
    "layout": "返回/紧凑内容身份→声音形式/时长/一句介绍→首屏加入与队列位置/总时长→适用情景→折叠具体介绍/提醒→原来源返回",
    "data": "nightContentDetail保存独立快照与returnRoute；当前可加入目录独立读取，原版本与现版本时长不同要明确提示；不通过nightChoice替换待播选择",
    "interaction": "加入后显示第几段/总时长并提供查看组合；正在播放时加入下次组合不改本次；版本变化先看清将加入的时长；折叠支持键盘；刷新/浏览器返回保持同项详情",
    "logic": "只提供日常放松内容说明，不承诺治疗/入睡，不假装已接试听音源",
    "exception": "加入先写成功再改队列；失败保留原组合，显示重试而非成功。下架内容解释不可加入并给其他内容入口；非法时长/空标题显示真实信息不完整，不渲染错误数据",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "复用NIG02路由，本地nightContentDetail及history.state.nightContentDetail",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07 用户已确认night-detail内容详情。本页专项启发式自评7.2→9.0/10；10组定向+6组组合回归通过。接续逐页审评NIG03，不改本页已确认布局。"
  },
  {
    "id": "NIG-03",
    "group": "夜间",
    "name": "自选内容",
    "route": "`/night/library`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-02 / NIG-05",
    "function": "将多个睡前内容加入组合",
    "layout": "返回→首屏待播/下次组合数量与总时长+查看组合→内容目录：介绍/已选顺序/明确加入移除→继续查看组合",
    "data": "已绑定8/12/30分钟及显式20分钟白噪音；未绑定只用公共5/10/15分钟",
    "interaction": "介绍与选择分开；加入后显示第几段，移除后可撤销恢复原顺序；成功保存才反馈，键盘操作保留同项焦点；刷新保留组合，从编辑进入原路返回",
    "logic": "只编辑nightPlan，不打断正在播放的session；不扩成付费内容商城",
    "exception": "加入/移除/撤销写入失败保持原组合，原位重试。空组合允许查看但不可播放；旧撤销与当前组合不一致时隐藏，不覆盖后续选择",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "nightPlan.ids去重后有序；libraryFeedback/撤销快照仅本次内存，校验前后组合一致；返回复用history.state.trail；night_plan_changed扩展action=undo，成功保存后记录，无新后台字段/服务",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "用户已确认night-library自选内容；启发式自评7.0→9.0/10，非真人研究。11组专项+10组详情+6组组合回归通过；后续逐页审评NIG04。"
  },
  {
    "id": "NIG-04",
    "group": "夜间",
    "name": "夜间播放器",
    "route": "`/night/player`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-05",
    "function": "按用户确认的组合顺序连续播放并保留进度",
    "layout": "返回/正式符号/状态与当前段→本段进度→上一段/播放暂停/下一段→整组进度→折叠本次组合及详情→渐弱状态/结束确认",
    "data": "开始时冻结tracks[]，各段id/title/duration/format/intro等与全局positionSeconds，当前段由累计时长派生",
    "interaction": "播放暂停居中，切段两侧；每段详情不切换播放。提前结束须确认，可取消，归档后进入历史；刷新/离开清除未提交确认。跨段自动更新，刷新/关闭重开保持同组/同位置；播完自动归档一次",
    "logic": "无隐形尾段；旧单段+20分钟尾段只派生一次。跳段使用播放进度措辞并不计完整播放奖励。编辑下次组合不改变快照",
    "exception": "切段保存失败原按钮重试，位置不变；暂停/归档失败保留本次会话并提示重试；内容快照与时长不一致不显示伪造进度/第0段且不自动归档；结束后的深链提供历史入口。真实音频/锁屏尚未接入",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "nightSession.tracks快照，skipped/stopReason；nightHistory归档原顺序与总时长，以sessionId去重",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "用户已确认night-player播放器；本页启发式自评7.3→8.9/10，不是真人测试。14组播放器行为及27组相邻回归核验；接续NIG05逐页审评，原型不输出音频。"
  },
  {
    "id": "NIG-05",
    "group": "夜间",
    "name": "编辑播放组合",
    "route": "`/night/sequence`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-02 / NIG-03",
    "function": "确认组合顺序及总时长",
    "layout": "返回→首屏段数/总时长/添加内容→有序编号列表与上移下移图标/独立移除→开始或返回当前播放器",
    "data": "唯一可编辑nightPlan.ids；tracks从当前目录解析，和当前session独立",
    "interaction": "按钮/键盘排序，首末约束；排序后同项焦点与新位置反馈；移除可撤销恢复原位置，后续编辑使旧撤销失效。每项详情/添加内容往返保留顺序，返回实际来源",
    "logic": "组合变化仅用于下一次手动开始；返回当前播放器只导航，不改变暂停状态或覆盖会话；移除到空仍不能开始",
    "exception": "排序/移除/撤销先写成功再更新；失败原顺序和总时长不变，可重试本次操作。刷新不恢复失败操作；开始保存失败不生成虚假会话。空态仍能添加",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "继续nightPlan v1；editorFeedback(expected/id/message/retry/undo)仅内存，撤销校验当前组合一致；复用night_plan_changed的move/remove/undo成功事件，无新增持久字段/一级入口/会员规则",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08 night-editor已获用户确认，继续NIG06。启发式自评6.8→9.0/10，不等同实客评分；保留其他已确认页面。"
  },
  {
    "id": "NIG-06",
    "group": "夜间",
    "name": "唤醒设置",
    "route": "`/night/wake-settings`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-04",
    "function": "预览并保存唤醒时间、提前窗口和声音；区分草稿、已保存与真实闹钟能力",
    "layout": "返回/标题→唤醒开关→最迟时间→智能叫醒准时/20/30分钟单选→戒指检测范围一行说明→声音→稍后提醒1–15分钟→权限→保存/恢复→折叠说明及唤醒预览",
    "data": "wakeDraft/wakeSettings(enabled,time,window,sound,snoozeMinutes)、wakeSaved、通知演示状态、设备连接；snoozeMinutes默认5，整数1–15；window=0为准时，不是关闭提醒",
    "interaction": "调整即暂存草稿；范围实时更新并标跨午夜前一天；显式保存才改有效设置；改时间/声音/窗口/时长不取消当前稍后提醒，不重算dueAt；关闭时若有稍后提醒须确认同时取消，取消或保存失败均保持原提醒；恢复上次保存；声音/权限往返不丢草稿，原路回夜间或SET02",
    "logic": "原型只保存设置，不执行浅睡检测/系统闹钟或承诺唤醒；准时与窗口为不同方式，关闭开关需保存。有效时间/窗口/声音校验；保存失败有效值不变，草稿失败警告并阻止App内离开；无绑定无设置控件，暂断连不是解绑",
    "exception": "无效时间禁保存但允许关闭；草稿/保存/恢复失败各自可恢复，权限关闭可存设置但不自动开通知；低电量、连接中、同步中、蓝牙关闭和断连分开说明，准时模式不显示浅睡信号提示；跨午夜正确；真实后台/音频/系统调度待原生联调",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08 night-wake-snooze已获用户确认，继续NIG07；简化及稍后提醒版启发式自评9.0/10，非实客或原生可靠性评分。局部night-wake-page.js/.css；复用页面/业务字段，window增加0、snoozeMinutes为1–15。smart_wake_settings_saved只记本机，未外发。"
  },
  {
    "id": "NIG-07",
    "group": "夜间",
    "name": "唤醒声音选择",
    "route": "`/night/wake-sound`（NIG-06 的子页）",
    "priority": "P0",
    "parent": "NIG-06",
    "function": "试听并选择唤醒声音；确认后带回设置草稿，不直接改已保存闹钟",
    "layout": "返回/标题→四种音色单选及独立试听按钮→状态反馈→使用所选声音→返回/保存说明和示意音提示",
    "data": "wakeSoundSelection(ownerAccount,baseSound,value)本机候选；wakeDraft.sound为设置草稿，wakeSettings.sound为有效值；试听加载/播放/错误状态只在内存",
    "interaction": "单选不自动播；每段可试听2秒，切换/停止/隐藏/离开即释放音频。候选刷新恢复；返回不确认；使用后回NIG06，再显式保存才生效。支持键盘方向键与44px触控",
    "logic": "已登录且绑定并开启唤醒草稿才可选择。候选按账号与原声音隔离；确认只合并声音，保留时间/窗口/稍后提醒。原型WebAudio合成音色非正式铃声，不设真实闹钟",
    "exception": "候选保存失败恢复旧选中并可重试；确认失败不导航或修改草稿。音频不支持/启动超时/中断明确反馈，仍可选声音；迟到音频回调不得在离开后播放",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08 night-sound已获用户确认，继续NIG08；《设计心理学》启发式自评6.1→8.9/10，非真实用户评分。14组专项及16组NIG06回归通过，console/page errors为空；无新外部API/埋点。正式音源与原生音量、静音模式、后台闹钟可靠性待后续提供/联调。"
  },
  {
    "id": "NIG-08",
    "group": "夜间",
    "name": "闹钟响起",
    "route": "原型独立全屏；正式版系统唤醒界面待双端联调",
    "priority": "P0",
    "parent": "系统调度",
    "function": "醒来时快速选择稍后提醒或结束本次；清楚区分待提醒、到时与已关闭",
    "layout": "无底部导航的深色全屏→退出预览→提醒状态/大时间/时间含义→再睡X分钟→我已起床→简短演示提示；等待显示日期与剩余分秒；已关闭给开始今天入口",
    "data": "只读已保存wakeSettings；wakeSnooze(ownerAccount,requestedAt,dueAt,minutes)使用UTC时间戳，按手机本地日期时间展示；新增wakeAlarmReceipt(ownerAccount,settingsKey,closedAt)记录本机本次预览关闭结果；snoozeUntil仅兼容显示",
    "interaction": "再睡1–15分钟从点击计时，等待禁重复；退出、刷新、重进保留绝对到时点，倒计时不逐秒朗读；到时可再延后。我已起床原子清稍后记录/记关闭结果后进NIG09，返回或刷新不重新响起；NIG06显式预览可再开始",
    "logic": "稍后提醒可超过最迟时间，不重新等浅睡；关闭本次不关长期设置。账号隔离关闭结果/稍后记录；未绑定、开关/权限关闭或设置非法不假装响铃；后续权限关闭仍可结束既有稍后记录。只演示，不输出健康结论或实际音频/通知",
    "exception": "延后/关闭/重新预览写入失败保留原状态并可原按钮重试；非法旧记录不展示倒计时；跨午夜展示日期。真实后台、静音、音量、戒指浅睡识别和系统唤醒可靠性仍待双端验证",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08 night-alarm已获用户确认，继续NIG09；《设计心理学》启发式自评7.0→9.0/10，非实客或原生可靠性评分。保留NIG06/NIG07已确认设计；原图和专项验证位于任务外部night-alarm-review。无新外部API或埋点。"
  },
  {
    "id": "NIG-09",
    "group": "夜间",
    "name": "醒来承接",
    "route": "`/night/morning` → 用户主动进入今日",
    "priority": "P0",
    "parent": "NIG-08",
    "function": "明确承接已关闭提醒，让用户直接开始今天，不强迫等待同步或填写记录",
    "layout": "回到夜间→正式超级符号/时段问候→有效关闭反馈或待提醒入口→前往今日主按钮→必要的记录/连接提示→次要播放记录入口",
    "data": "只读当前账号的wakeAlarmReceipt/wakeSnooze、硬件绑定、deviceStatus、蓝牙开关和dataLifecycle；本页不生成健康值、睡眠时长、趋势或新业务字段",
    "interaction": "前往TOD01；暂无数据/同步/断连去DEV10；未绑定去DEV01；基线阶段可去HLT00；回看NIG10、返回NIG01。提醒仍待处理时可回NIG08，不自动取消；刷新保留既有结果",
    "logic": "仅账号/设置匹配且同一本地日的有效关闭记录可展示本次已关闭；有有效稍后记录则优先给提醒入口。直达或旧日期不假称刚关闭。05–11时早上好，其余已关闭为醒来啦、直达为你好；暂无/部分记录仅给适用提示，健康数值由原有页面承接",
    "exception": "未绑定仍能浏览今日/公开内容/播放历史；同步中不假称完成；暂无数据不冒充生成中。真正闹钟关闭及后台调度仍待原生回执，本机结果不是原生执行证明",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08 night-morning已获用户确认，继续NIG10；design-everyday-things启发式自评6.5→8.9/10，非实客评分。12组专项+12组NIG08回归通过，console/page errors为空；本页只读，无新API/埋点。"
  },
  {
    "id": "NIG-10",
    "group": "夜间",
    "name": "最近夜间",
    "route": "`/night/recent`",
    "priority": "P1",
    "parent": "NIG-01 / 我的",
    "function": "按日期和感受状态找到一次收听，回看当时组合或继续记录感受",
    "layout": "播放历史标题→未结束播放入口（如有）→全部/未记/已记筛选→日期分组→单卡内结束状态、时间/进度、可展开内容、感受入口→选择内容",
    "data": "只读nightHistory的session快照、tracks/stopReason/skipped和按sessionId隔离的nightReviewDrafts；复用pageViews[NIG-10]新增nightHistoryOwner/nightHistoryFilter/nightHistoryOpen视图字段；旧单段仍兼容",
    "interaction": "按结束时间倒序展示，不改原数组；筛选刷新保留，存储失败留原列表；逐段进NIG02看旧快照；感受进TOD08，草稿继续/保存失败重试/返回后标签与筛选联动；展开项按sessionId恢复不按列表索引串位",
    "logic": "不按当前待播或当前硬件版本重算旧记录；含跳段只称播放进度，不称实际听完；异常时长不画假进度，缺内容只展示保留片段。有效播放到期后在页面重入或运行中按sessionId去重归档，不依赖先打开播放器；暂停不补时，跨账号/注册和损坏会话不自动补存；保留原选择与感受草稿。保存失败显示待保存与重试，不伪称还在播放。浏览和筛选不启动播放、不改健康数据",
    "exception": "真实空历史与筛选无结果有不同出口；未绑定可回看旧记录。旧数据无完整内容/时长时不给死入口或NaN。视图按账号隔离，但旧session缺明确账号归属，生产级账号隔离/迁移与跨端同步仍需后端确认",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "归档sessionId去重；逐段详情使用历史快照；无额外外发",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08 night-history用户已确认；design-everyday-things启发式自评6.6→9.0/10，非实客评分。14组专项+12组NIG09回归通过；保留已确认TOD08/NIG02/NIG04设计。新增局部night-history-page.js/.css，未新增外部API/埋点。"
  },
  {
    "id": "NIG-11",
    "group": "夜间",
    "name": "夜间异常说明",
    "route": "`/night/help` · 复用 NIG-11 独立帮助页",
    "priority": "P0",
    "parent": "NIG-01 / NIG-04",
    "function": "用户侧显示夜间帮助：辨别问题、查看相应设置、回到原播放流程",
    "layout": "深色画布；当前问题与主操作；戒指/播放/唤醒三行状态；两项折叠说明和客服入口",
    "data": "只读绑定、deviceStatus、bluetooth/notification、nightSession原快照、wakeSettings；wakeSnooze复用账号校验；pageViews沿用top/open",
    "interaction": "NIG01/NIG04自然入口；按状态去DEV10/DEV01、NIG04/NIG01/NIG10、NIG06/PERM01/NIG08；客服HELP03；刷新返回原来源",
    "logic": "无播放不显示继续；损坏播放不自动恢复/替换；设置取wakeSettings而非草稿；蓝牙关闭优先；未绑定也可看公共内容帮助；只导航不调度设备或闹钟",
    "exception": "未绑定、蓝牙关闭、连接中、断连、同步中、低电量、需处理、未知状态、无播放/暂停/损坏、通知关闭、非法唤醒时间、他人稍后提醒",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08 night-support用户已确认；design-everyday-things自评6.0→8.9/10，非实客评分。专项15/15+播放历史14/14+唤醒设置16/16通过。新增局部night-support-page.js/.css及必要返回接线；无新增业务字段/API/埋点。音频/后台/系统闹钟的真实错误回调仍待原生集成验收，不伪造已恢复或已安排。"
  },
  {
    "id": "NIG-12",
    "name": "智能睡眠联动",
    "route": "`/night/smart-sleep-link`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-04",
    "note": "2026-09-08 night-fade用户已确认；design-everyday-things启发式自评6.1→9.0/10，非实客评分。15组专项+15组帮助+16组唤醒回归通过。无新增业务字段/API/埋点；只演示偏好和会话同步，不执行真实入睡检测、音频调节或闹钟。计时起点/时长/目标音量与实时信号规则仍待产品、算法和原生确认。",
    "group": "夜间",
    "function": "用户侧聚焦音量渐弱，说明作用范围；唤醒保持独立入口",
    "layout": "音量示意、标题、单开关/已开关状态、作用范围、保存结果、当前会话、独立唤醒与帮助入口",
    "data": "toggles.sleepFade与有效当前nightSession.fadeEnabled；只读wakeSettings、绑定/连接/蓝牙；旧会话保留兼容，明确他人或注册批次不符的会话不修改",
    "interaction": "开关立即写入后更新界面，失败保持原值并可重试；新播放承接偏好；NIG01/NIG04自然入口；NIG06/NIG11/DEV10刷新返回本页及原来源",
    "logic": "沿用旧有当前+后续播放范围，但原子保存不先改内存；不变更暂停/位置/队列/唤醒/通知/历史；未绑定无开关且旧动作拦截；渐弱与闹钟独立",
    "exception": "存储失败/重试/离开；未绑定、断连、蓝牙关闭、当前会话损坏/已结束/明确他人；唤醒草稿不冒充有效时间",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "当前app.js渐弱逻辑、已确认NIG01/04/06及本目录README；原docs/product/app-specs路径在当前工作区不存在"
  },
  {
    "id": "HAL-01",
    "group": "Halo AI",
    "name": "Halo 首页与对话",
    "route": "`/halo`",
    "priority": "P0",
    "parent": "Tab",
    "function": "从一句话开始对话，按明确来源理解记录并选择下一步",
    "layout": "新对话/历史/设置页头；空态IP与三个起手问题；聊天态缩小IP；可查看和移除的来源；独立滚动消息；固定输入、工具与额度说明",
    "data": "会话ID、messages、draft、context、source快照；身体参考同时受硬件/数据质量/设置门控；用户记录与设备数据分开",
    "interaction": "输入与草稿恢复；历史/新对话；＋进入HAL-05/06；来源查看/移除；暂停或归档后明确继续；放松行动进入NIG-01选择内容，不自动播放",
    "logic": "只重做HAL-01，保留HAL-02/05/06完整页与旧数据。新对话不串来源；移除当前来源不关闭全局身体参考；未绑定按北京时间每天10条普通消息，安全帮助保留",
    "exception": "空白消息禁发；额度用尽保留草稿；中文输入法不误发；刷新、切页与新对话保留草稿。当前为同步本地示例回复，真实模型超时/重试需接入后验收",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认；头部顺序按反馈改为新对话、历史、设置。正式符号与IP沿用，不新增一级入口；继续逐页审阅MY-01"
  },
  {
    "id": "HAL-02",
    "group": "Halo AI",
    "name": "历史对话",
    "route": "`/halo/conversations`",
    "priority": "P0",
    "parent": "HAL-01",
    "function": "查找、查看与管理已保存对话，不在此发送消息",
    "layout": "返回/新对话、标题与内容搜索、全部/草稿/已归档筛选、日期/状态/摘要列表、逐项管理弹层",
    "data": "conversations与原消息/草稿/来源/status/updatedAt；activeConversationId、conversationQuery；不新增健康值或AI回复",
    "interaction": "搜索/清空、筛选、打开、暂停/继续、归档、取消优先的删除确认；刷新保留已保存变更",
    "logic": "查看不改时间或状态；仅修改指定对话；删除须当前页面/弹层令牌/最新记录一致且本机保存成功；其他会话和独立用户记录保留",
    "exception": "全空/筛选空/搜索无匹配分别提示；存储失败可重试；跨页/账号更新拦旧动作并提示刷新；缺失日期不造数",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "HAL-02已获用户确认，接续HAL-03；保留HAL-01及HAL-05/06完整页。仅本地历史管理，服务端同步与删除仍待接入"
  },
  {
    "id": "HAL-03",
    "group": "Halo AI",
    "name": "Halo 记忆",
    "route": "`/halo/memory`",
    "priority": "P0",
    "parent": "HAL-01 / HAL-08",
    "function": "确认、修改、删除已记录记忆及控制使用偏好，不等于本次对话上下文",
    "layout": "简洁页头、使用开关、待确认/已确认分组、逐条操作、编辑与删除弹层；身体解读反馈单独折叠",
    "data": "haloMemories原记录/确认状态与可核对来源；haloMemoryDrafts账号绑定草稿；toggles.memory；不自动生成记忆或健康值",
    "interaction": "确认；编辑草稿/稍后再改/保存并确认/放弃；暂停使用；取消优先的单删/清空；查看真实关联来源；返回Halo设置",
    "logic": "确认前不作为跨会话参考；关闭使用不删除记录；可靠保存后才更新原记忆；仅本机CRUD，不宣称已检索/云端删除",
    "exception": "空内容禁存并说明；草稿可刷新恢复；失败保留内容并重试；跨页/账号变化拦旧覆盖；取消、离开和旧确认不能删除；未知来源不猜测",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08用户已确认；保留聊天、感受与戒指记录。自动提案、跨会话检索与云端同步待后端接入；接续HAL-04审评"
  },
  {
    "id": "HAL-04",
    "group": "Halo AI",
    "name": "主动陪伴设置",
    "route": "`/halo/proactive`",
    "priority": "P0",
    "parent": "HAL-08 / SET-02",
    "function": "选择Halo主动提醒与不打扰时段，不改动闹钟及身体数据",
    "layout": "简洁页头、通知权限状态、总开关与两项偏好、静默时段卡片、范围说明折叠",
    "data": "与SET-02共用toggles.proactive/morningPrompt/nightPrompt；按账号保存quietHours/quietDraft；haloQuietHours为当前账号镜像；独立notification权限",
    "interaction": "总开关联动；静默编辑/校验/草稿恢复/取消/保存重试；权限页往返；回到真实来源",
    "logic": "总开关关闭保留子项；未允许通知仍可保存偏好；静默时段可靠保存后更新；跨午夜标明次日，不影响wakeSaved/闹钟/设备报告提醒",
    "exception": "空时间或起止相同禁存并说明；草稿刷新恢复；写入失败不显示成功；跨页更新/账号变更防旧覆盖；同日和跨日静默都可设置",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "系统通知权限与推送服务；本机原型未调用真实送达能力",
    "rules": "独立权限、总子开关联动、静默优先、可靠保存；不改变闹钟",
    "backend": "账号提醒偏好、触发策略、时区与送达状态",
    "owner": "产品+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08用户已确认；12组隔离浏览器检查通过，自审8.8/10；原型不发送真实通知。正式触发频次、时区与系统送达由后端/双端确认；接续HAL-05审评"
  },
  {
    "id": "HAL-05",
    "group": "Halo AI",
    "name": "情绪与感受记录",
    "route": "`/halo/feelings`",
    "priority": "P0",
    "parent": "HAL-01 / HAL-08",
    "function": "记录此刻感受；选择仅保存或显式带入Halo，不自动发送消息",
    "layout": "简洁页头、五个可选感受图标、文字记录、保存反馈、已存记录折叠、固定双操作",
    "data": "按账号保存haloFeelingEditor草稿与稳定draftId；haloFeelingRecords用户记录；haloSource绑定recordId/文本/账号/记录时间及带入时间",
    "interaction": "单选可取消、单独文字输入；刷新恢复草稿；仅保存/保存并聊；回看与复用原记录；返回真实入口",
    "logic": "未绑定可记录，不触发会员奖励；草稿不修改对话来源；可靠写入后清草稿，重复操作不新增记录；暂停/归档原会话不变",
    "exception": "空白禁止保存并说明；失败留原输入可重试；跨账号/并行页变化拦旧覆盖；旧版草稿与记录保留；删除后不引用旧来源",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08用户已确认天气图标版；按用户记录与设备数据分离，不新增强度或诊断字段。保存和带入不代表已调用真实AI；服务端存储/幂等/隔离待接入"
  },
  {
    "id": "HAL-06",
    "group": "Halo AI",
    "name": "我的小计划",
    "route": "`/halo/journeys`",
    "priority": "P0",
    "parent": "HAL-01 / HAL-08",
    "function": "明确开始后按自己的节奏记录小计划，不要求连续打卡",
    "layout": "简洁页头和更多、双主题、七天进度、具体练习、可折叠感受/历史、固定当前主操作",
    "data": "haloJourneyStore按账号保存选中主题、返回入口及独立记录；本轮ID/状态/日期/用户感受、历史轮次；完成保留当时做法与文字快照",
    "interaction": "选择并开始、记录今天完成、降低难度、今天先不做、暂停/继续；结束/重开/删除二次确认，返回真实来源",
    "logic": "每主题每轮同日不重复，七天完成；暂停/结束保留记录，重开收进历史；删除仅清本主题。操作不自动播放内容、改变手机设置、发送通知或触发会员奖励",
    "exception": "未开始/暂停/结束/已完成不能打卡；失败保留原进度与输入可重试；账号/并行页面变化拦旧写；取消和过期确认不执行；刷新和切主题保留状态",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08用户已确认。旧进度/感受/状态保留，无开始证据的初始计划不自动报名；启发式自评5.2→8.8/10。服务端存储/幂等/账号隔离和正式提醒能力待接入"
  },
  {
    "id": "HAL-07",
    "group": "Halo AI",
    "name": "Halo 数据与隐私",
    "route": "`/halo/data-privacy`",
    "priority": "P0",
    "parent": "HAL-01 / HAL-08",
    "function": "分开查看本次参考、调整参考偏好和管理Halo内容",
    "layout": "简洁页头、本次参考卡、身体/记忆开关、记忆/聊天入口、折叠保存说明及独立清空入口",
    "data": "复用haloSource、toggles.haloBody/memory和原记录；haloPrivacyView保存账号、真实返回入口、子页入口及本机清空时间",
    "interaction": "移除本次参考不删原记录；开启偏好不替换本次来源；替换已有参考二次确认；管理记忆/聊天可返回；清空取消/确认/失败重试",
    "logic": "无数据不显示健康值/趋势或身体带入按钮；暂停/归档不改原历史来源；只清空当前账号本机聊天、记忆、感受及对应草稿，不伪造云端删除回执",
    "exception": "写失败不改原数据；过期/旧版确认不执行；账号和并行页变化拦旧覆盖；归属未核对时不显示他人来源并禁止清空",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-08用户已确认；启发式自评4.8→8.8/10，非真人研究。不恢复健康数据单次授权旧规则。小计划、身体解读反馈、戒指健康数据与商业资产保留；真实云端存储/删除与生产账号隔离待接入"
  },
  {
    "id": "HAL-08",
    "name": "Halo 设置",
    "route": "`/halo/settings`",
    "priority": "P0",
    "parent": "HAL-01 / MY-01",
    "note": "2026-09-08用户已确认；启发式自评5.0→8.8/10，非真人研究。语音/生日个性化无实现，不提供虚假开关或授权引导；不新增一级入口",
    "group": "Halo AI",
    "function": "集中管理Halo体验偏好并到达会话、感受、小计划、提醒、记忆、隐私和帮助",
    "layout": "三项常用入口、对话体验、日常陪伴、记忆与隐私、帮助分组；图标与当前状态配合",
    "data": "复用haloPreferences、inspiration开关及通知/记忆真实偏好；haloSettingsView保存账号、返回入口、子页来源、表达草稿与基线",
    "interaction": "表达示例实时预览、暂存/刷新恢复/放弃/保存；今日灵感独立开关同步首页；7个子入口刷新后可返回；紧急帮助与客服分开",
    "logic": "保存后才改变后续表达，不改聊天历史；不读取生日/健康数据生成个性化；未接入语音仅静态标注；提醒状态反映总开关、权限和子项",
    "exception": "失败保持原偏好可重试；跨页/账号与商业状态变化拦旧写；旧表达草稿与新已存偏好冲突时要求放弃再改；小屏可滚动与键盘焦点可见",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "RHY-01",
    "group": "节律",
    "name": "节律首页",
    "route": "`/rhythm`",
    "priority": "P0",
    "parent": "节律 Tab",
    "function": "四类周期标记：实际经期、预测经期、预计排卵日、预计易孕期；感受独立记录，周期功能选填",
    "layout": "预计经期或当前经期卡、四类周期月历、仅显示周期的所选日卡、单一感受入口（随所选过去日期补记/修改）；经期操作复用弹层。感受预览不混入周期卡",
    "data": "新增rhythmCycleData.version/accounts[owner].events/draft/initialized；事件含id/ownerAccount/startDate/endDate/status/source/revision。沿用rhythmHomeView及感受草稿；预测为派生值，不写成实际记录",
    "interaction": "未来3个月可浏览，只有今天与过去可记录；经期开始/结束/未知结束日、补记/修改/删除后更新月历与预测；关闭刷新保草稿，保存失败留弹层重试；感受仍在RHY-03编辑",
    "logic": "仅用已确认开始日+常见周期估算一次预计经期，预计结束日按持续天数估算；逾期不滚出虚构周期；旧开始日不补造实际持续天数；暂停/冲突/无资料不预测。无硬件门槛或奖励；新增未验证日历排卵/易孕估算，仅用于原型演示，不确认生理事件",
    "exception": "未来/逆序/重叠日期、未结束记录重复、草稿冲突/失败、账号隔离、删除残留、暂停、预计日期已过、短屏与键盘",
    "ios": "保留页面体系，待原生日历/键盘与读屏验证",
    "android": "保留页面体系，待原生日历/键盘与读屏验证",
    "sdk": "无强制硬件依赖；仅用户输入记录",
    "rules": "实际记录与日期估算分开，不确认已排卵、不用于避孕；未标记日期不代表安全期；日期演示不冒充戒指检测",
    "backend": "本地日历估算与单次原子提交模拟；真实预测服务及验证、跨端版本、存储事务和删除回执待接入；不借用其他品牌算法",
    "owner": "产品+双端+后端",
    "source": "本目录README / rhythm-home-page.js / rhythm-cycle-store.js / rhythm-cycle-page.js / prd/05与prd/18周期范围",
    "note": "2026-09-08按用户纠正补齐四类周期标记及解释弹层，移除周期图例内感受分类但保留原内容与独立入口。新估算为派生值，不存实际事件。仅本地、待确认。"
  },
  {
    "id": "RHY-02",
    "group": "节律",
    "name": "读懂感受记录",
    "route": "`/rhythm/stage`",
    "priority": "P0",
    "parent": "RHY-01",
    "function": "知道所选日期记下了什么，以及如何回日历对照其他日期",
    "layout": "所选日记录/空态、三条图文回看方法、折叠说明；有确认周期时标题为周期与感受",
    "data": "本人有效已保存rhythmRecords；selectedRhythmDate；rhythmHomeContext扩展02/06的owner/date；pageViews复用按日期/账号的展开与位置",
    "interaction": "展开补充原文与说明；回日历定位原日；有记录才查看RHY-06确认预览，确认后才带入Halo；返回/刷新/前后退保留日期",
    "logic": "用户记录与设备测量分开，不推断阶段、不新增曲线或身体数值；没有记录不显示Halo入口；未确认/暂停周期不展示默认周期结果",
    "exception": "空记录、未确认/暂停/冲突周期、删除中/删除残留、外账号与未来记录、Halo源更新/删除失效、保存浏览位置失败",
    "ios": "本地原型已实现，原生控件与读屏待真机验收",
    "android": "本地原型已实现，原生控件与读屏待真机验收",
    "sdk": "无需绑定硬件；仅用户输入记录",
    "rules": "单一确认，不自动传入周期设置或设备信息",
    "backend": "本地模拟记录，真实多账号与多端更新/删除待接入",
    "owner": "产品+双端+后端",
    "source": "本目录README / rhythm-guide-page.js / app.js",
    "note": "2026-09-07用户已确认RHY-02（5.8→8.8分），接续RHY-03。保留原route及现有页面体系，不上线/提交/打包。"
  },
  {
    "id": "RHY-03",
    "group": "节律",
    "name": "感受记录编辑",
    "route": "`/rhythm/record` · 独立编辑页",
    "priority": "P1",
    "parent": "RHY-01",
    "function": "按所选日期保存或修改感受；可以只写文字，不强制选标签",
    "layout": "明确日期、四个可取消单选快捷标签、正文与字数、删除分区；独立滚动和固定保存栏",
    "data": "本人当日记录及草稿；inspect安全字段/dirty/conflict；原草稿对象增加可选baseSignature，baseSavedAt语义不变",
    "interaction": "单标签或纯文字均可保存；输入就地更新字数/按钮/草稿状态；未修改禁存；返回刷新恢复；删除二次确认；冲突明确放弃草稿后看最新",
    "logic": "纯文字feeling为空、labels为空，不伪造情绪；双存储事务失败不假报成功；按账号/日期隔离，未来不可写；删除只影响当日，聊天原文独立保留",
    "exception": "空白、无修改、超长、写入失败/回滚、旧草稿迁移、同时间戳内容更新冲突、外账号/删除中不显示旧原文、窄屏及键盘",
    "ios": "本地原型已实现，原生键盘/读屏与持久化待接入",
    "android": "本地原型已实现，原生键盘/读屏与持久化待接入",
    "sdk": "不依赖硬件绑定；用户记录不作为设备数据",
    "rules": "只编辑感受，不把经期预测写成用户记录；实际经期日期统一在RHY-01弹层编辑。保留暂停/删除边界，无奖励",
    "backend": "本地事务模拟；真实多端更新/删除和鉴权待接入",
    "owner": "产品+双端+后端",
    "source": "本目录README / rhythm-editor-page.js / rhythm-record-store.js",
    "note": "2026-09-07用户已确认RHY-03（6.2→8.8分），接续RHY-04。不重设计已确认首页/说明页，无Git/上线/打包。"
  },
  {
    "id": "RHY-04",
    "group": "节律",
    "name": "节律设置",
    "route": "`/rhythm/settings`",
    "priority": "P0",
    "parent": "RHY-01 / 我的",
    "function": "管理记录模式、可选周期设置和提醒",
    "layout": "两种记录方式、日期及天数、经期预测/临近提醒开关、感受提醒与权限入口、管理记录；独立滚动和固定保存栏",
    "data": "rhythmSettingsEditor按账号区分saved/draft/base；新增prediction及periodNotice布尔值，旧值分别默认true/false；感受提醒仍用toggles.rhythmNotice",
    "interaction": "模式/日期/预测/提醒统一保存后生效；实际经期已有记录时开始日期只读并链接RHY-01修改；草稿可返回刷新继续，放弃须确认；暂停仅明确恢复",
    "logic": "只记录感受不强迫填周期；切模式保留合法记录及参数；原子保存失败不变；经期记录更新同步已保存开始日，不覆盖脏设置草稿；开关变化不冒充重新确认周期；删除不复活旧内容",
    "exception": "无日期、未来日期/非整数/越界、存储失败、草稿冲突、跨账号、暂停/删除和短屏",
    "ios": "本地可交互原型；原生日期键盘/读屏/提醒排程待接入",
    "android": "本地可交互原型；原生日期键盘/读屏/提醒排程待接入",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "沿用20–45/2–10整数输入边界，不宣称医学正常范围，不预测排卵/安全期；不新增健康授权或奖励",
    "backend": "本机草稿与提交模拟；真实多端版本控制、提醒排程及注销清理新缓存待接入",
    "owner": "产品+双端+后端",
    "source": "本目录README / rhythm-settings-page.js / rhythm-settings-store.js",
    "note": "原RHY-04已确认；2026-09-07仅随周期闭环补预测/经期临近提醒与日期单一编辑入口。提醒演示偏好与页内提示，不实际发送通知；不Git/上线/打包。"
  },
  {
    "id": "RHY-05",
    "group": "节律",
    "name": "节律记录管理",
    "route": "`#RHY-05` · 独立管理页 / 删除确认弹层",
    "priority": "P0",
    "parent": "RHY-01 / RHY-04",
    "function": "按日期纠正和删除，或管理全部节律数据",
    "layout": "按天管理入口；周期展示状态与暂停/恢复；进入设置；全删独立区域与范围确认；空态/失败/成功反馈",
    "data": "本人有效感受日期数、设置与草稿；删除快照增加本人rhythmCycleData事件/草稿，确认token只存内存绑定账号与目标快照",
    "interaction": "查看日历不改模式或暂停；暂停恢复即时反馈且失败不变；模式统一回RHY04保存；删除先核范围可取消/失败重试，离页撤销确认",
    "logic": "仅删本人及兼容旧版节律内容，并删除本人实际经期/草稿，关闭感受提醒与周期预测/临近提醒；普通记录/显式外账号/硬件/会员及聊天正文保留；单事务成功后才报完成",
    "exception": "无内容禁删、旧删除残留、未保存设置或冲突、健康删除或注销中、确认后数据/身份变化、两存储失败、浏览器返回和短屏",
    "ios": "本地交互已实现；真机读屏/返回手势与云端删除回执待验收",
    "android": "本地交互已实现；真机读屏/返回键与云端删除回执待验收",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "不按感受标签误删普通记录；不恢复被删原文；无新增健康授权或奖励；模式仍回设置保存，暂停隐藏预测但允许主动查看历史",
    "backend": "本机事务与幂等模拟；真实鉴权、多端版本、删除任务及备份回执待接入",
    "owner": "产品+双端+后端",
    "source": "本目录README / rhythm-management-page.js / rhythm-management-store.js",
    "note": "2026-09-07用户已确认；原4.8→复评8.8分。本页状态保留，接续RHY-06；不Git/上线/打包。"
  },
  {
    "id": "RHY-06",
    "group": "节律",
    "name": "带着这条记录聊聊",
    "route": "Deep Link",
    "priority": "P0",
    "parent": "RHY-01 / RHY-02",
    "function": "核对一条用户记录，确认后带入新的Halo对话，不自动发送消息",
    "layout": "日期与用户记录标记、感受和完整原文；独立滚动预览；固定带入/取消区",
    "data": "当前账号所选日期的有效rhythmRecords；来源快照含date/recordId/recordSavedAt/ownerAccount/text；既有conversations/chat/haloDraft/haloSource；pageViews按日期+账号恢复滚动",
    "interaction": "从RHY-01/02进入；取消返回原日期；确认先原子保留旧对话与草稿，再打开HAL-01新对话；来源详情和移除复用现有入口；失败留页重试",
    "logic": "带入仅所选一天的日期、感受和补充原文，不附带周期设置或设备数据；无自动发送/扣额度/空会话历史；记录或选日变更须重新核对；不覆盖旧会话来源",
    "exception": "空/已删/跨账号/注销或健康删除中无可用带入；旧会话内容冲突须核对；保存失败内存和历史不变；暂停周期仍可引用有效用户记录",
    "ios": "按本地原型实现原子交接与返回/进程恢复，原生能力待真实端验收",
    "android": "按本地原型实现原子交接与返回/进程恢复，原生能力待真实端验收",
    "sdk": "不依赖健康SDK；用户记录来源确认不是新增健康数据授权",
    "rules": "只引用本人当前有效快照，旧消息原文不修改；旧无归属原型记录兼容不等于后端多账号鉴权",
    "backend": "会话/草稿保存与新来源原子交接、记录版本复核、归属鉴权和跨设备一致性需对接真实服务",
    "owner": "产品+双端+后端",
    "source": "本目录README / rhythm-halo-page.js / rhythm-halo-handoff.js",
    "note": "2026-09-08用户已确认，原6.0→独立复评8.8分；最新22浏览器/17交接/13来源测试通过。RHY-01～RHY-06本轮全部确认，仅保留本地原型，不自动推进其他模块、不Git/上线/打包。无新增一级入口、顶层持久业务字段或分析埋点。"
  },
  {
    "id": "MY-01",
    "group": "我的",
    "name": "我的首页",
    "route": "`/me`",
    "priority": "P0",
    "parent": "Tab",
    "function": "管理个人资料、设备、会员账户、订单与体验，快速找到设置和帮助",
    "layout": "我的与客服；可点击资料行；设备摘要；会员账户及任务/Points/权益；订单与体验；更多服务；直接展开的设置与帮助；页尾说明入口",
    "data": "profile.nickname；硬件激活/配对/蓝牙/连接状态；currentMemberAssetSnapshot等级与可用积分；pendingPointsCorrection；studioHomeRecords；channelJoinNext申请阶段",
    "interaction": "资料ACC-01；设备DEV-01/05/10；会员MEM-01、任务MEM-04、Points PTS-01、权益MEM-07；订单直接SEL-10；Studio STU-08；顾问按当前步骤续接；设置与帮助不折叠",
    "logic": "复用会员及顾问状态判断，不另算资产、不因激活写成升级；解绑保留等级，暂时断连不等于解绑；尚未提交的顾问申请不显示审核中；仅active进入经营中心，暂停/终止进入历史结算",
    "exception": "无独立可信电量字段不显示固定76%；待冲正展示可用0和使用暂停但可查明细；暂无预约不伪造记录；无健康数据不展示健康值；详情页本轮只复用入口",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07用户已确认；只重排MY-01与必要摘要，不增加一级入口；页尾保留会员说明与服务说明弹层。后续逐页推进ACC-01等详情"
  },
  {
    "id": "ACC-01",
    "group": "我的",
    "name": "个人资料",
    "route": "`/me/profile`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "编辑昵称和选填身体资料，单独选择生日权益提醒偏好",
    "layout": "返回与个人资料标题；昵称；选填身体信息和用途说明入口；出生日期与带单位的身高体重；生日权益提醒开关；固定保存与撤销修改区域",
    "data": "profile已保存资料；profileEditor独立草稿/编辑基线/触碰字段/保存时间；birthdayBenefit偏好；basicProfile首次资料状态",
    "interaction": "输入只写草稿；返回或刷新恢复时明确提示，继续编辑后切回未保存状态；保存后才更新我的昵称和资料；撤销草稿前确认；生日权益提醒随本页保存，不自动开启或影响已有权益；用途弹窗不修改资料",
    "logic": "昵称非空即可，允许单字；身体字段选填，有值时校验真实出生日期不晚于北京时间今天、身高100–230cm、体重25–250kg。范围仅为现有原型输入约束，正式范围待产品/硬件确认；用途仅说明显示年龄及保存用户基础资料，不承诺健康计算准确度",
    "exception": "未来/无效日期及非法数值行内提示；首次有效资料可保存一次，已保存且无改动显示已保存并禁用；保存守卫登录和注销状态；ONB-04另存后保留双方编辑并明确确认冲突，不静默覆盖；旧资料保留，不猜测清空",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07逐页审阅第3页，待用户确认；保留当前设计体系，不新增头像上传或健康算法；仅改昵称不强制完成首次身体信息，生日关怀不承诺发放积分；真实后端保存与多账号隔离未接入"
  },
  {
    "id": "DEV-10",
    "group": "设备",
    "name": "我的 Halo 硬件",
    "route": "`/me/device`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "查看和管理本账号 Halo 硬件，完成重连、同步与异常恢复",
    "layout": "标题与返回；正式符号、当前查看设备与连接状态；设备事实摘要；状态对应主操作；已绑定设备和连接另一枚入口；位置偏好与线索；固件、佩戴、高级操作入口。状态模拟仅在App外审阅面板",
    "data": "deviceHub按账号隔离查看选择、设备事实、权限偏好与请求/结果；deviceBindings账号归属；pairedDevice当前设备；deviceLastSyncedAt当前设备兼容字段；deviceWearGuide复用现有佩戴设置/回看来源",
    "interaction": "已连接可同步、断连可重连、蓝牙关闭可查看权限设置；请求处理中可离开并刷新恢复，失败可重试；查看另一枚不等于切换当前连接；位置开启前单独确认、无记录显示空态；佩戴回看看完返回本页",
    "logic": "未知电量/连接时间/同步时间不填示例；重连与同步回执分开、无回执不宣称同步完成；设备事实不得跨设备复制；断连不解绑或改会员资产；定位不实时、不响铃/震动/亮灯，开启偏好不生成地址",
    "exception": "未绑定、解绑保留、配对待激活、权限拒绝、暂时断连、同步失败、孤立旧处理中状态、异步刷新恢复、账号/设备归属变化；与绑定、活动同步、固件、测量及重置互斥",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "2026-09-07逐页审评后按用户确认的五项实施，待用户验收原型。保留此前精简方向：六种状态模拟、任务去重与会员后台规则不投放App页面；高级操作保留DEV-12；仅联动DEV-04回看返回及共用权限/操作守卫。仍是本地模拟，不代表真实BLE/定位接入"
  },
  {
    "id": "DEV-11",
    "group": "设备",
    "name": "设备信息",
    "route": "`/me/device/info`",
    "priority": "P0",
    "parent": "DEV-10",
    "function": "查看当前戒指的信息、检查与安装固件更新",
    "layout": "精简设备身份、已读事实、更新主操作与自动阶段、设备支持的数据类型",
    "data": "deviceFirmware：账号+设备隔离的 installedVersion/versionReadAt、availableVersion/checkStatus/checkedAt、电量及资格回执、request ID/targetId/targetVersion/phase/readyAt/result；mockDevice 仅为本地模拟",
    "interaction": "检查更新→自动读取版本与电量；开始更新→下载/传送/安装/版本确认；帮助只读；结果不确定时查询原请求，不重复安装",
    "logic": "已安装版本仅由读取回执更新，再次检查不回退；旧全局状态不作为版本依据；操作互斥；刷新重入恢复原请求；未知/过期电量先读取，SDK 资格判定能否更新",
    "exception": "检查失败、下载失败、安装结果待确认、断连、权限不足、低/未知电量、忙碌、多设备/账号切换、缓存损坏；不宣称未经回读的成功或设备可用",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "电量、同步、固件/硬件版本、绑定状态、能力状态"
  },
  {
    "id": "DEV-12",
    "name": "高级设备操作",
    "route": "`/me/device/advanced`",
    "priority": "P0",
    "parent": "DEV-10",
    "note": "清除设备记录、恢复出厂、本机移除和账号解绑分别确认；计步重置收于客服协助",
    "group": "设备",
    "function": "明确目标、先同步保护记录、按能力开放维护操作并查询本次结果",
    "layout": "设备身份与尾号、能力检查、戒指数据/连接与账号分组、客服协助折叠、按设备操作历史",
    "data": "deviceMaintenance.accounts[account].devices[id]：target/boundAt、checkedAt/accountCheckedAt/capabilities/records、request id/kind/scope/consent/status/mode/readyAt/applied、history；账号核对与设备读取分开，本地模拟回执不等于真实SDK能力",
    "interaction": "选中设备→按操作核对条件→确认后果→自动回执；本机移除不需蓝牙，解绑仅需联网核对；清除类显式勾选；取消仅在发送前；离页/刷新恢复原请求，未知结果只查询同请求",
    "logic": "不靠重置推断解绑；本机移除保留账号归属；解绑只改目标，剩余激活设备维持账号active；保留既得资产/健康历史；操作互斥与原目标恢复重连",
    "exception": "能力未知/不支持、未同步未知、断连、低电量、权限/网络、操作冲突、结果未知、账号/归属变化、损坏缓存；无硬件仍保留原账号结果页",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "SET-01",
    "group": "我的",
    "name": "数据与隐私",
    "route": "`/me/data-privacy`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理系统权限、位置偏好与明确范围的本机演示记录；其他数据分别管理",
    "layout": "权限与使用、本机导出与删除、戒指和其他记录入口、折叠保存说明、按结果反馈",
    "data": "dataPrivacy.version/ownerAccount/accounts[account].draft/request；请求id/账号/scope/counts/fingerprints/consentAt/status/readyAt；deviceHub账号位置权限与偏好；导出时固定内容快照",
    "interaction": "位置复用原授权结果；导出一次确认明文及条数；删除先选范围再确认不可恢复；自动本机结果、刷新恢复、失败重试；云端未接不假完成",
    "logic": "本机档案账号与显式记录归属校验；不删除账号/会员/设备/Studio/节律；仅撤掉被删除记录的后续来源引用，不改历史对话；实际本地写入后才报告完成",
    "exception": "空记录、位置未申请/拒绝/关闭、保存失败/回滚、记录变更、账号不符、损坏旧请求、旧申请无回执、测量进行中；本机操作可离线",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "逐页审阅：原页面快照先保存，建议自审后实现；目标大于8.5，当前待用户确认修改稿。不恢复全局单次健康授权，不把本地成功当作云端或真机成功"
  },
  {
    "id": "SET-02",
    "group": "我的",
    "name": "通知与夜间设置",
    "route": "`/me/notifications-night`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理睡眠目标与提醒偏好，区分权限、偏好、已保存闹钟和未保存修改",
    "layout": "权限状态；睡眠目标概览与编辑弹层；闹钟入口；Halo 主动提醒与静默时段；设备与报告提醒",
    "data": "sleepNotifications.accounts[accountRef]：goal/configured/preferences/draft/savedAt；sleepGoal 已保存兼容字段；notification/proactive/子偏好；wakeSettings 与 wakeDraft；haloQuietHours",
    "interaction": "目标编辑、校验、暂存恢复、保存/失败重试、确认放弃；偏好即时保存；权限页完成回原页；进入 NIG-06/HAL-04 并返回",
    "logic": "目标保存不生成闹钟或睡眠记录；父提醒关闭保留子选择；权限关闭保留偏好但不承诺送达；闹钟摘要只读已保存状态，草稿另标；成功写入才发布结果",
    "exception": "未设置；空时间、同起止禁保存；计划在床时长与目标不同仅提示；离页/刷新草稿恢复；写入失败保留原值；账号隔离；未绑定不生成健康数据",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "本机交互演示，不发送通知或响铃；系统通知授权沿用 PERM-01 演示状态。真实权限、通知送达、闹钟调度和跨端冲突需双端/后端确认；SET-02 修改稿等待用户确认"
  },
  {
    "id": "SET-03",
    "group": "我的",
    "name": "通用设置",
    "route": "`/me/settings`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理动态效果与 Halo 表达偏好，预览桌面小组件并查看当前语言和单位",
    "layout": "简洁标题；常用设置；语言/单位只读信息；表达偏好与小组件弹层",
    "data": "toggles.reduceMotion、系统 prefers-reduced-motion；haloPreferences.tone/length；账号内存草稿；当前身体天气与连接状态",
    "interaction": "降低动画即时保存/失败重试；表达选择→示例→明确保存/取消；关闭小组件预览留在原页；返回我的",
    "logic": "偏好只影响之后回复，不改历史；系统减少动画优先；固定语言与公制单位不伪造切换；小组件仅预览、不承诺添加或系统面板",
    "exception": "存储失败保留原值与选择；账号变化拒绝旧草稿保存；未绑定或无数据不生成健康值；短屏弹层可滚动",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "SET-03 修改稿待确认；保留 HAL-08 现有完整页但共用表达偏好弹层。无真实小组件安装/模型接入，未扩展全 App 翻译和单位切换"
  },
  {
    "id": "HELP-01",
    "group": "我的",
    "name": "使用帮助",
    "route": "`/me/help`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "先查看常见问题解答，再进入对应处理页面；找不到答案仍可反馈或联系客服",
    "layout": "简洁标题、搜索、分类、可展开问答、始终保留的反馈与客服入口",
    "data": "固定问答内容、helpQuery、helpCenter 分类/展开状态/返回来源；读取当前设备与数据状态，不生成健康事实",
    "interaction": "搜索/清空/分类/展开答案；进入现有处理页面；真实页内返回恢复查询与展开；无结果仍能联系客服",
    "logic": "搜索忽略大小写并支持常见别名；中文输入不重建输入框；连接排查进入现有设备管理，不直接重新绑定；支持页面本身不提交工单或发送信息",
    "exception": "无结果提供清空和客服动作；刷新恢复搜索；未绑定不造数据；非帮助入口不被旧返回来源劫持",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "HELP-01/02/03 已确认。客服渠道沿用企业微信，真实工单/会话服务尚未接入"
  },
  {
    "id": "HELP-02",
    "group": "我的",
    "name": "问题反馈",
    "route": "`/me/feedback`",
    "priority": "P0",
    "parent": "HELP-01 / MY-01",
    "function": "整理并保存本机问题记录，查看历史；需要处理时进入企业微信联系指引",
    "layout": "填写、反馈记录、记录详情三个视图；问题类型、必填描述、当条日志选择、保存结果与客服入口",
    "data": "feedbackFlow.accounts[account] 草稿/视图/记录ID/滚动位置；feedbackTickets 的 ownerAccount、类型、正文、保存时间、日志选择、local-draft 状态；主动勾选后的 commerceContext 仅含账号、来源页、订单/售后ID",
    "interaction": "填写与字数反馈、保存/失败重试、查看记录/详情、继续草稿、联系指引、按来源返回；刷新恢复本机内容；订单/售后新反馈自动归类，单号需主动勾选后附带，跨单咨询不覆盖原草稿",
    "logic": "仅本机保存，不代表已发给客服；写入成功才生成记录并清草稿。日志每新条默认关闭，当前不采集上传。当前账号只显示明确归属的新记录；无归属旧数据保留但不显示正文",
    "exception": "空白与超1000字不可保存；超长不截断。存储失败保留输入并提示重试/勿关闭；重复点击不重复保存；中文组合输入不中断；无记录有真实空态",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "HELP-02 已确认，接续 HELP-03。没有截图上传、自动发送、云端工单或客服处理回执；正式 App 需后端接入"
  },
  {
    "id": "HELP-03",
    "group": "我的",
    "name": "企业微信人工客服",
    "route": "`/me/support` · 当前为本地联系说明",
    "priority": "P0",
    "parent": "HELP-01 / HELP-02 / 设备 / Studio / 渠道 / 注销结果",
    "function": "说明客服渠道与当前可用动作，保留原问题上下文并返回来源",
    "layout": "人工客服页头、渠道简介、入口不可用状态、问题反馈/常见问题替代动作、已有客服会话说明与隐私提示",
    "data": "supportContact 同账号来源页及反馈引用；commerce含经原记录核对的sourceRoute、orderId、afterSaleId、ownerAccount；读取注销/渠道状态，不生成工单或健康信息",
    "interaction": "从各入口直接进入单页；订单/售后来源显示关联单号，先记下问题或返回原申请；返回时恢复精确订单/售后选择；展开已有会话说明；刷新后按真实来源返回",
    "logic": "未提供核验客服链接/二维码时不伪造接通，不用未经核验的搜索指引。联系动作不上传正文；注销/终止合作仍可查看支持说明，不要求重新激活；按钮受当前账号权限约束",
    "exception": "客服入口缺失提供可用替代；注销态不显示被守卫阻止的反馈/帮助动作；来源不明或账号变化不沿用旧上下文",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "HELP-03 已确认。真实联系仍缺经核验的官方链接或二维码；本轮不配置外部服务、不创建 service_ticket，不把打开本页标记为已交接客服。正式客服权限、业务系统回执与失败回退须接入验收"
  },
  {
    "id": "LEGAL-02",
    "group": "首次使用",
    "name": "关于与协议",
    "route": "`/me/about-legal`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "识别当前 App 原型版本，查看协议入口、服务主体信息与健康用途说明",
    "layout": "简洁页头、正式超级符号与字标、App1.0/原型v6.5标识、协议入口、折叠主体信息、健康用途短说明",
    "data": "公开品牌资产与原型版本；history.state.aboutLegalContext 同账号来源；不读取或伪造设备固件，不新增业务数据",
    "interaction": "进入已确认的 LEGAL-01 或注销态三份只读文档；展开主体信息；关闭阅读、刷新及返回均保持正确来源",
    "logic": "App原型标识不冒充正式安装版本；品牌不冒充法定运营主体，缺失信息明确待补充。阅读不等于同意，不改变登录勾选、权限、健康或会员状态",
    "exception": "未绑定/解绑不出现虚构固件；注销中仍可直接阅读；无有效同账号来源回我的或账号安全；完整法律正文及主体待确认，不伪造配置",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "LEGAL-02 已确认。仅重做关于页与必要来源返回，保持 LEGAL-01/阅读层/登录同意既有实现；正式App版本、法定主体和完整协议仍需正式资料接入，不代表法律合规验收"
  },
  {
    "id": "ACC-02",
    "group": "我的",
    "name": "账号与安全",
    "route": "`/me/account`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "查看当前登录账号，安全退出本机登录，或进入独立注销说明/进度",
    "layout": "简洁页头、脱敏登录手机号、本机登录说明、退出动作、独立注销入口；退出前确认及原处失败重试",
    "data": "有效 authPhone、signedIn/authVerified、临时登录请求与 accountDeletionStatus；不伪造设备型号或服务端登录设备列表",
    "interaction": "退出前确认/取消；可靠保存后退出，失败重试；注销仅进入 ACC-03，已提交显示查看进度；返回受现有账号权限约束",
    "logic": "退出不注销账号、不清业务记录与草稿；成功清临时验证码/登录请求并阻止旧回调复活。确认绑定当前会话和实际弹层，旧动作不能绕过；正式服务端会话撤销未接入",
    "exception": "手机号缺失如实显示；存储失败保留会话可重试；其他页面更换账号或保存新记录时停止退出并提示刷新，不能覆盖新数据；刷新/取消不确认；重复/过期确认不生效；注销中可查看进度",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "ACC-02 已确认。退出仅本地原型行为；正式鉴权、设备会话及多端撤销仍需后端和双端接入。注销影响与演示进度复用 ACC-03"
  },
  {
    "id": "ACC-03",
    "group": "我的",
    "name": "注销账号",
    "route": "Full Screen / Dialog",
    "priority": "P0",
    "parent": "ACC-02",
    "function": "查看注销完成后的影响与当前资产，确认本地演示申请并查看演示记录",
    "layout": "简洁页头、影响提示、六类资产、折叠说明、二次确认、演示记录与客服入口",
    "data": "当前账号、本机只读会员资产、accountDeletionStatus及本地模拟记录；不冒充后台工单或完成回执",
    "interaction": "查看影响；确认默认取消；可靠保存后记录演示申请，失败原处重试；刷新查看记录；账号/客服往返",
    "logic": "沿用会员v1.20第10.1节，注销完成后资产失效，不以订单/退款/售后/申诉阻止申请；本原型不删除真实账户或资产，不假称已受理",
    "exception": "资料缺失如实显示并可重读；读写失败不变状态；确认绑定账号/会话/当前弹层/资产，旧动作及跨页变化不覆盖；旧演示状态不补造日期",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "ACC-03 已获用户确认，接续HAL-02。仅演示确认与保存记录，真实受理、即时/最长15工作日、数据删除与法定留存均待后台/法务接入；不新增注销门槛"
  },
  {
    "id": "STU-08",
    "name": "Halo Studio 首页",
    "route": "`/me/studio`",
    "priority": "P0",
    "parent": "MY-01 / Deep Link",
    "note": "逐页审阅：首页按真实记录提示继续事项；我的体验面板、活动分类、扫码；不新增一级入口",
    "group": "Halo Studio",
    "function": "选择活动，继续预约/体验/报告，查看全部已有预约记录",
    "layout": "标题与扫码、我的体验入口、按状态显示的继续卡、分类和图片活动列表",
    "data": "现有studioRecords及活动快照；分类筛选；时间、地点、公开价格和名额；场地图片为AI生成原型示意",
    "interaction": "分类筛选；打开我的体验面板；选择记录进入对应支付/预约/体验/报告页；扫码复用STU-01",
    "logic": "首页不生成预约/支付/报告/奖励；取消退款优先判断；报告等待/失败直接到STU-12；保留未知旧记录且不回退成其他活动",
    "exception": "无记录、分类无可预约活动、取消退款、报告未就绪、个人记录删除、未知旧活动；面板关闭/焦点恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-01",
    "name": "扫码或输入体验码",
    "route": "`/me/studio/code`",
    "priority": "P0",
    "parent": "STU-08 / Deep Link",
    "note": "默认空输入；查找活动后进入核对，不把查找到活动当成预约已核验",
    "group": "Halo Studio",
    "function": "输入或扫码找对应活动，手动核对信息；已有预约可直接查看",
    "layout": "活动码输入、查找状态、扫码备用入口、取码帮助、找到的活动摘要、固定核对动作",
    "data": "haloStudioCodeLookup按账号保存draft/status/requestId/eventId；查找状态idle/querying/found/missing；不写入交易或会员资产",
    "interaction": "查找→同页结果→STU-02；空输入禁用，Enter查找；错误可改码重试，返回/刷新恢复；已有预约→STU-07；演示码仅右侧审阅区填入",
    "logic": "沿用现有示例码与活动映射；结果不创建预约、不确认已付；修改输入即失效旧结果；STU-02需匹配已找到的活动；本地演示查询不代表后台核验",
    "exception": "离线保留输入；保存失败不声称找到结果；读取失败不展示旧结果；相机未接入时明确提示并聚焦手动输入；未核验深链回STU-01",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-09",
    "name": "活动详情",
    "route": "`/me/studio/experiences/:id`",
    "priority": "P0",
    "parent": "STU-08 / STU-01",
    "note": "活动介绍、时间地点、主理人和价格；按预约状态提供一个下一步",
    "group": "Halo Studio",
    "function": "帮助用户判断是否参加，并进入同一场活动的确认预约或已有记录",
    "layout": "图片、活动名与简述、时间地点和名额、主理人、准备事项；取消/到场/报告折叠说明；常驻价格和主动作",
    "data": "selectedStudioEventId、现有活动快照与 studioRecords；当前场次为本地示例，图片/介绍/用品建议未获真实场地方确认，完整地址与资质不编造",
    "interaction": "未预约去 STU-16，不直接建单；已有记录按状态继续；咨询复用 HELP-03，其他渠道预约先去 STU-01 核验；折叠、返回与刷新保留",
    "logic": "未绑定可预约；名额/开始时间/金额在展示、详情点击及建单时校验；已取消不清空记录重约；报告不自动授权也不保证生成",
    "exception": "满额/已开始/非法时间或金额禁用新预约并给其他活动入口；未知 ID 不回退瑜伽；已有待付款过期先查看原预约；真实锁位与支付回调留预约页后续审阅",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-02",
    "name": "核对活动与预约",
    "route": "`/me/studio/experiences/:id/confirm`",
    "priority": "P0",
    "parent": "STU-01 / STU-09",
    "note": "活动信息核对与机构预约核验分开；已有记录不重建",
    "group": "Halo Studio",
    "function": "展示同一活动时间/地点/时长/主理人；核验当前账号的机构预约；核验成功后进入参加准备",
    "layout": "活动缩略图与标题、图标信息行、核验状态卡、付款取消说明、固定主操作、换码与客服入口",
    "data": "studioInstitutionChecks按eventId保存账号、lookup上下文、requestId、attempt、status、outcome、原记录快照和活动快照；成功记录institutionReceipt及participationConfirmed；金额未知为null",
    "interaction": "idle→checking→verified/notfound/unknown/review；成功停留结果页→STU-10；原记录按状态继续；查询同一请求、保存失败重试、刷新/退出恢复，不自动勾选用途",
    "logic": "共用Studio锁内重读，核对账号、活动、lookup上下文与原记录未变后单次保存核验结果及预约；不覆盖已有订单/取消/退款/个人记录；兼容paid=true仅表示机构参加资格已确认，不代表App收款",
    "exception": "未知结果不建单；未找到可重试；离线提示；存储失败不显示成功；并发新预约保留；已结束活动转人工核对；深链无匹配体验码回STU-01；模拟状态选择仅审阅区",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-16",
    "name": "确认预约",
    "route": "`/me/studio/experiences/:id/book`",
    "priority": "P0",
    "parent": "STU-09",
    "note": "逐页审阅：核对本场、选券与金额，再提交预约；不虚构锁位分钟数",
    "group": "Halo Studio",
    "function": "确认同一场活动与应付金额；付费去 STU-17，免费或券抵扣后去 STU-18",
    "layout": "活动缩略图与场次摘要、1位参与、体验券、费用明细、可展开取消说明；底部常驻金额与主动作",
    "data": "studioRecords 内 selectedVoucherId/useVoucher、bookingRequest(id/status/readyAt/quote/outcome)、bookingError；成功后 baseAmount/voucherDiscount/dueAmount/eventSnapshot/voucherId；复用按活动的 pageViews",
    "interaction": "券默认不选、明确切换；提交中防重、失败保留原选择可重试、离开/刷新恢复；报价变化须再次核对，券失效不自动替券或转现金；既有记录只继续，不重建",
    "logic": "免费场不消费券；提交和完成时重新校验时间/名额/价格与同一券ID；成功后写入完整预约，失败不留下交易编号。0.9秒为本地模拟请求，不是实际锁位或支付",
    "exception": "无券/不适用/失效、提交失败、满额/过期/未知活动、已有取消退款；本页读取会员既有资产，不赠券、不自动授权。券有效期仅尊重已有字段，不新设政策",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-17",
    "name": "支付与结果",
    "route": "`/me/studio/orders/:id/pay`",
    "priority": "P0",
    "parent": "STU-16",
    "note": "原预约金额付款；失败可重试，结果未知只查单，不重复付",
    "group": "Halo Studio",
    "function": "核对并支付同一预约；成功留在本页确认结果，再查看预约",
    "layout": "金额与结果优先、活动缩略信息、原费用明细、折叠订单信息；常驻主动作与稍后支付/查看",
    "data": "studioRecords中的baseAmount/voucherDiscount/dueAmount；paymentRequest(id/bookingId/status/amount/quoteKey/attempts/readyAt/outcome/startedAt/completedAt/error)、paymentError与原paidAmount/paidAt；可选payable/paymentExpiresAt",
    "interaction": "支付→处理中→成功/明确失败/取消支付/结果未知；未知只查询，失败可重试；刷新和退出恢复同一请求，离开不抢回页面",
    "logic": "已付/免费/券抵扣不重复付款；金额无效、未知活动、已开始、外部来源、取消退款/删除状态禁止新支付；已发起请求不因过截止停止查单，关联冲突保留未知并引导客服；本地0.9秒演示不是真实扣款或锁位",
    "exception": "结果未知时包括我的预约入口在内均先核对支付，不直接取消或再次付款；付款渠道、实时库存/锁位、服务端付款期限、回调查单与晚到支付对账待后端确认，不自行设置期限",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-18",
    "name": "我的预约与退款",
    "route": "`/me/studio/bookings/:id`",
    "priority": "P0",
    "parent": "STU-08 / STU-17",
    "note": "逐页审阅：原预约、参加准备、二次确认取消、现金与原券分别查结果",
    "group": "Halo Studio",
    "function": "核对原预约和必要交易信息；查看参加准备不等于到场；确认取消后查询原申请",
    "layout": "状态、活动缩略图、时间地点时长、原实付；订单与取消说明折叠，底部主动作与次级取消",
    "data": "原bookingId/eventSnapshot/paidAmount/source；明确refundableAmount；refundRequest冻结eventId/bookingId/amount/quoteKey/voucherId与status/stage/readyAt/attempts；voucherReturn独立状态；refundedAmount不覆盖原实付",
    "interaction": "取消只开确认，保留预约不写流水；提交/查单/返券可刷新恢复，禁止重复；准备页与个人数据删除隔离",
    "logic": "未知活动不回退其他预约；来源由记录判断；报价不明先核对不默认全退；现金和返券独立且幂等；申请结果可跨截止查询",
    "exception": "支付未知时先查支付；截止/非法时间/缺金额/错单均防错；删除个人记录保留必要交易与合法退款；本地适配器不处理真实退款",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-10",
    "name": "参加准备 / 本次设置",
    "route": "`/me/studio/participations/:id/consent`",
    "priority": "P0",
    "parent": "STU-18 / STU-04 / STU-15",
    "note": "参加前保存本次选择；已开始或完成只管理原设置，不重启活动",
    "group": "Halo Studio",
    "function": "说明活动记录用途；可选本人戒指报告，无戒指也可参加",
    "layout": "活动摘要、参与方式、活动记录、可选报告与设备状态、折叠说明、固定操作栏",
    "data": "eventId/bookingId、preparationDraft/baseKey、mode、activityConsent/healthConsent、consentVersion/consentChanges、reportReviewState、recordingStoppedAt",
    "interaction": "选择仅存草稿；明确下一步或保存才生效；撤回先确认；刷新返回保留；活动后保存返回原体验",
    "logic": "精确预约核验；拒绝报告可不使用戒指继续；不改变历史参与方式、不签到；重新开启不自动恢复历史报告",
    "exception": "错单/未付款/取消/删除拦截；草稿冲突不覆盖；断连可去设备或改为不使用戒指；低电量提醒；保存失败保留草稿",
    "sdk": "复用已绑定设备状态；正式设备身份与活动级有效记录待 SDK 接入",
    "rules": "本次用途与报告结果分离；联系和营销保持独立；不恢复已删除的全局单次健康授权规则",
    "backend": "正式预约归属、许可版本与撤回回执、报告访问与恢复审核待接入；当前仅本机演示",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-11",
    "name": "活动前的感受",
    "route": "`/me/studio/participations/:id/reflection`",
    "priority": "P0",
    "parent": "STU-10",
    "note": "一句可跳过的用户记录；空白与未改动不重复保存，保存成功才继续",
    "group": "Halo Studio",
    "function": "记录活动前的主观感受，基础参与也可用；不填写不影响参与与已有权益",
    "layout": "原活动摘要、单一文本框、草稿/保存反馈、折叠原文与用途、固定主次操作",
    "data": "feelingDraft(eventId/bookingId/baseKey/text/updatedAt)、beforeFeeling/beforeSavedAt/beforeUpdatedAt/beforeVersion、beforeRecordScope、beforePreviousRecords",
    "interaction": "空白跳过、新文保存、未修改继续、清空保留原记录；删除需确认；失败原位重试；旧文字仅显式复制为草稿",
    "logic": "保存前校验预约与活动阶段；正式正文和草稿分离；报告/详情/用户记录导出只读当前预约已保存正文；开始后不可补写活动前感受",
    "exception": "保存配额失败不跳页；刷新/关闭恢复草稿；预约/保存版本冲突须确认放弃草稿再核对；旧归属不明内容保留，不自动认领",
    "sdk": "无强制硬件 SDK",
    "rules": "用户记录与设备/AI分开；无内容埋点、不奖励签到、不改变会员或报告资格",
    "backend": "本机原子保存模拟；正式账号/预约归属、并发版本、云端保存删除、历史保留仍待接入",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-03",
    "name": "开始前确认",
    "route": "`/me/studio/participations/:id/preflight`",
    "priority": "P0",
    "parent": "STU-10 / STU-11",
    "note": "核对本次活动、参与方式与感受后显式开始；不等于签到",
    "group": "Halo Studio",
    "function": "开始前最后确认，不重复收集同意或强制填写感受；保存开始记录成功后进入 STU-04",
    "layout": "原预约活动摘要、参与方式与动态连接态、感受保存态、到场后开始提示、固定主按钮",
    "data": "eventSnapshot、bookingId、mode、activityConsent、healthConsent、有效 beforeRecordScope；sessionId、sessionScope、startedAt；不把草稿当正式记录",
    "interaction": "调整返回 STU-10、查看感受返回 STU-11；未就绪可调整或显式确认不使用戒指；有效上一场可继续；重复点击不重复启动",
    "logic": "同一浏览器锁内重读当前记录、身份和设备事实，核对已展示基线并原子提交开始与可选降级；无效旧会话不永久拦截；低电量只提醒，历史基线不足不拦活动开始",
    "exception": "保存失败留页重试且不改变原模式；跨窗取消、换单、删除、撤回或连接变动须重看；锁不可用拒绝无锁启动；刷新/重开恢复原 sessionId 与开始时间",
    "sdk": "原型仅模拟本机状态；正式需本人设备身份、佩戴/信号质量回执与服务端会话幂等，不把已连接宣称为佩戴或质量通过",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-04",
    "name": "活动进行中",
    "route": "`/me/studio/sessions/:id`",
    "priority": "P0",
    "parent": "STU-03",
    "note": "低打扰参与，分清活动计时与戒指状态；显式确认结束",
    "group": "Halo Studio",
    "function": "查看活动经过时间与本次记录状态；离开不结束；结束需二次确认并成功保存",
    "layout": "原活动摘要、大字号经过时间、参与方式/连接/记录停止状态、离开提示、固定结束按钮",
    "data": "startedAt推算经过时间（不是采集时长）；sessionId/Scope/AccountRef、mode、同意/停止时间；结束写completedAt、elapsedSeconds、completionSnapshot",
    "interaction": "返回Studio首页稍后继续；设置复用STU10，连接复用设备页；取消结束不改记录，确认结束成功到STU12；重复操作恢复原结果",
    "logic": "同源会话锁内重读完整记录并校验账号/预约/会话和确认基线；原子写结束及完成快照，不自动签到/发奖励；新完成活动的报告资格只认本场匹配回执，不由以后全局基线或绑定变化补造",
    "exception": "保存失败留页重试；跨窗换单/撤回/删除/退款须核对；断连不自动结束或切参与方式；无有效开始时间显示待核对；退出刷新不重置时间",
    "sdk": "本地原型仅模拟；正式接入本人设备采集回执、佩戴/信号质量和服务端会话幂等，不展示伪实时健康值",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-12",
    "name": "本次活动与报告状态",
    "route": "`/me/studio/participations/:id/report-status`",
    "priority": "P0",
    "parent": "STU-04 / STU-08",
    "note": "本次参与结果、报告进度与可恢复出口",
    "group": "Halo Studio",
    "function": "区分已保存参与与报告结果，不以报告生成作为查看权益的前提",
    "layout": "原预约摘要、报告状态、一个主动作、本次记录与活动权益、返回Studio",
    "data": "本场completionSnapshot/captureReceipt、reportStatus、reportRequest、reportCheckedAt；明确新旧历史边界",
    "interaction": "查询与重试可恢复、结果后查看报告；返回Studio→我的体验和本次记录均可回来",
    "logic": "按活动/预约/会话/账号核对；旧generated只读保留，旧waiting不凭后来硬件生成；不改奖励与采集",
    "exception": "查询中、仍在整理、查询未知、生成失败、无报告、撤回、删除、身份不符与保存失败分别处理",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-05",
    "name": "课后报告",
    "route": "`/me/studio/participations/:id/post-report`",
    "priority": "P0",
    "parent": "STU-12",
    "note": "本次活动事实、身体记录空态与独立用户记录",
    "group": "Halo Studio",
    "function": "看清已有活动事实与用户记录，没有测量内容时不补造趋势",
    "layout": "原预约摘要、活动时长与参与方式、身体数值空态、用户记录、可选后续、固定返回",
    "data": "本场startedAt/completedAt、mode、已保存且scope匹配的beforeFeeling；报告资格不等于已有测量数据",
    "interaction": "返回本次活动/Studio/记录/权益；次日到期才提供查看；图表示例单独打开、切指标和读数、关闭",
    "logic": "无身体数值不画个人曲线；局部虚构示例不写账本；旧generated只读，不补造历史；不证明课程效果",
    "exception": "未生成、撤回、删除、身份或归属变化退回状态页；无效完成时间不进入次日；离线只读可用",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-06",
    "name": "次日回顾",
    "route": "`/me/studio/participations/:id/next-day-report`",
    "priority": "P0",
    "parent": "STU-05",
    "note": "固定活动次日与数据来源，不以今日状态替换历史回顾",
    "group": "Halo Studio",
    "function": "回看本场活动次日已保存的睡眠、身体天气和睡眠基线对比",
    "layout": "原预约、结束日与回顾日、状态、三个可展开指标、说明、本次记录与权益、固定返回课后报告",
    "data": "completedAt北京时间次日；可选nextDayReport精确账号/场次/预约/会话/结束时间/日期及来源匹配，不读全局今日样例",
    "interaction": "展开指标来源与对比图；重读本机记录不假装网络同步；返回课后报告/Studio/本次记录/权益",
    "logic": "未到日期/暂无记录/记录不足/已可读分别呈现；完整睡眠、身体天气及基线齐备才显示数值；示例明确标注，不能证明活动效果",
    "exception": "日期无效不崩溃；来源不匹配不显示健康值；身份变化、撤回或删除退回状态页；跨窗、离线与重入保护",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-13",
    "name": "本次奖励",
    "route": "`/me/studio/participations/:id/benefit`",
    "priority": "P0",
    "parent": "STU-12 / STU-05 / STU-06",
    "note": "本场积分与成长分开核验、实际到账与限额说明",
    "group": "Halo Studio",
    "function": "确认本次是否到账、各得多少、如何查看明细",
    "layout": "活动摘要、核验状态、积分/成长双栏、折叠到账信息与说明、固定查询/明细及返回",
    "data": "账号/活动/预约/完成快照；benefitRequest；同源studioAwards与pointsTransactions实际积分、成长、offset、available、occurred_at/posted_at",
    "interaction": "查询进度可离开或刷新恢复；本场明细弹层进入全部积分明细；返回本次活动、体验与客服",
    "logic": "仅独立核验回执驱动新增奖励；未绑定可得Points但成长0；UTC+8发生月4次与常规2000上限；原子持久化/幂等；健康授权/报告生成不作为奖励条件；旧资产先查后判新增",
    "exception": "未完成、待核验、查询中/无结果、限额、部分到账/待冲正抵扣、遗留部分回执、明确调整、退款待核对；源失败不回写旧资产，账号/预约错配不展示",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-14",
    "name": "联系设置",
    "route": "`/me/studio/participations/:id/contact`",
    "priority": "P0",
    "parent": "STU-15",
    "note": "机构联系仅受控中继，不开放手机号、微信或名单导出",
    "group": "Halo Studio",
    "function": "分别管理本次服务消息与后续活动推荐，不改变报告或奖励",
    "layout": "本次活动摘要、两个独立开关和当前状态、折叠联系方式保护、固定保存反馈及返回/客服",
    "data": "contactConsent、marketingConsent；contactPreferences记录账号/活动/预约、version、updatedAt、lastChanged、localOnly",
    "interaction": "开关即保存；成功后显示本机保存反馈，失败保留原值可重试；关闭不再二次确认；返回本次体验",
    "logic": "默认不勾选、不继承其他场次；只读展示不创建授权；明确归属和精确预约范围，写入前重读并局部合并；消息由Halo转发，不开放联系方式；健康与奖励独立",
    "exception": "读/写失败、跨窗新值、账号或预约更换、旧授权范围不匹配不误开；已删除记录可关闭旧设置但不能重新开启；本地保存不冒充云端授权回执",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-07",
    "name": "最近体验",
    "route": "`/me/studio/history`",
    "priority": "P0",
    "parent": "STU-08",
    "note": "我的预约与记录；全部、待参加、已完成、取消与退款四类筛选",
    "group": "Halo Studio",
    "function": "按场次找回预约、支付、取消退款、体验、报告与奖励入口",
    "layout": "标题与刷新、记录计数、四类筛选、场次状态卡、固定活动入口",
    "data": "studioRecords 中已有预约及完成记录；eventSnapshot、bookingId、accountRef、sessionScope、支付/退款/报告/删除状态；筛选仅存当前会话",
    "interaction": "Studio首页我的体验→STU-07；按当前状态进入STU-16/17/18/04/05/12/15；记录与奖励进入STU-15；刷新只读",
    "logic": "账号与场次匹配后展示；点击重读并校验预约标识；报告使用统一资格判断；取消记录保留，已删除个人内容仅开放必要预约记录；不重建不存在的历史预约",
    "exception": "区分无记录、筛选无结果与读取失败；跨账号不展示、失效卡不跳转；未知活动转客服；不改写会员资产或活动状态",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-15",
    "name": "本次体验",
    "route": "`/me/studio/participations/:id`",
    "priority": "P0",
    "parent": "STU-07 / STU-08",
    "note": "单次体验汇总、报告与奖励入口、个人记录管理",
    "group": "Halo Studio",
    "function": "回看本次参与方式、实际时长、报告、已保存用户记录及关联奖励；管理本次个人内容",
    "layout": "场次摘要、参与状态、报告主卡、用户记录、奖励/预约/联系/记录用途入口、次要删除入口、固定返回按钮",
    "data": "按账号+eventId+bookingId+sessionId核对studioRecords；奖励读取既有账本回执；personalDeletedAt、personalDeletionScope记录本地删除范围与时间",
    "interaction": "报告→STU-05或STU-12；奖励→STU-13；预约→STU-18；联系→STU-14；记录用途→STU-10；返回→STU-07；删除同页二次确认，可取消或失败重试",
    "logic": "删除前锁内重读并比较完整记录，单次保存成功后才显示已删除；清理本次感受/草稿/报告请求/采集凭据/次日回顾，保留必要交易和奖励核验摘要；不自动申请云端删除、不改变资产或其他场次",
    "exception": "读取失败与无效归属不展示旧内容；确认后数据变化则中止删除；保存失败保留原记录；刷新不自动恢复删除意图；已删除不恢复报告或重开删除按钮",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  }
];
