window.HALO_V5_PAGES = [
  {
    "id": "SYS-01",
    "group": "首次使用",
    "name": "启动与会话恢复",
    "route": "App Launch",
    "priority": "P0",
    "parent": "系统",
    "function": "恢复会话并路由到正确起点",
    "layout": "中央品牌状态；超时后给重试与离线查看",
    "data": "登录会话、绑定引用、配置、上次摘要",
    "interaction": "自动恢复；失败重试或只读进入",
    "logic": "并行读取本地状态；按登录/授权/绑定分流",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "双端有根状态；需补品牌/错误状态"
  },
  {
    "id": "ONB-01",
    "group": "首次使用",
    "name": "价值与边界说明",
    "route": "`/onboarding/intro`",
    "priority": "P0",
    "parent": "SYS-01",
    "function": "说明核心价值与非医疗边界",
    "layout": "2-3 个轻屏；主按钮开始使用",
    "data": "价值说明、健康与 AI 边界",
    "interaction": "继续或已有账号登录",
    "logic": "登录前不请求蓝牙、通知和健康权限",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "远端未形成完整独立流程"
  },
  {
    "id": "AUTH-01",
    "group": "首次使用",
    "name": "手机号登录",
    "route": "`/auth/login`",
    "priority": "P0",
    "parent": "SYS-01",
    "function": "手机号登录",
    "layout": "手机号、验证码、协议、登录按钮",
    "data": "手机号、验证码状态、协议版本",
    "interaction": "发送验证码、登录、打开协议",
    "logic": "频控与风控；登录失败保留输入",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "账号/验证码",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "双端已有基础页"
  },
  {
    "id": "AUTH-02",
    "group": "首次使用",
    "name": "验证码确认",
    "route": "`/auth/otp`",
    "priority": "P0",
    "parent": "AUTH-01",
    "function": "确认验证码",
    "layout": "验证码输入、倒计时、错误提示",
    "data": "验证码、倒计时、错误码",
    "interaction": "提交、重发、换号",
    "logic": "验证码幂等与频控；账号授权不得串号",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "账号/验证码",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "多为登录页内部状态"
  },
  {
    "id": "LEGAL-01",
    "group": "首次使用",
    "name": "协议与健康/AI说明",
    "route": "`/legal/consent`",
    "priority": "P0",
    "parent": "ONB-01",
    "function": "取得协议与健康/AI授权",
    "layout": "协议列表、独立勾选、继续按钮",
    "data": "协议 ID/版本、同意状态",
    "interaction": "阅读、同意、返回",
    "logic": "保存版本与时间；撤回后相应能力降级",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "需按真实协议版本和勾选状态实现"
  },
  {
    "id": "PERM-01",
    "group": "首次使用",
    "name": "权限用途说明",
    "route": "`/permissions`",
    "priority": "P0",
    "parent": "LEGAL-01",
    "function": "逐项说明并请求系统权限",
    "layout": "蓝牙、通知、后台/闹钟权限卡",
    "data": "权限用途和系统状态",
    "interaction": "逐项允许、去设置、暂不",
    "logic": "只在用户点击时触发系统弹窗",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "按系统能力逐项管理且可撤回；不采用健康数据单次/逐次重复授权；设备绑定可跳过"
  },
  {
    "id": "DEV-01",
    "group": "设备",
    "name": "连接戒指引导",
    "route": "`/device/connect`",
    "priority": "P0",
    "parent": "PERM-01 / 我的",
    "function": "发起戒指连接",
    "layout": "戒指视觉、状态、单一主按钮、帮助",
    "data": "蓝牙权限、连接状态",
    "interaction": "开始扫描、查看帮助",
    "logic": "无能力时不展示灯光、震动、ECG 等入口",
    "exception": "未授权、无设备、多设备、弱信号、断连、同步失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "双端已有设备页基础"
  },
  {
    "id": "DEV-02",
    "group": "设备",
    "name": "扫描与选择戒指",
    "route": "Sheet",
    "priority": "P0",
    "parent": "DEV-01",
    "function": "扫描并选择目标戒指",
    "layout": "扫描进度、设备列表、信号、刷新",
    "data": "设备名/标识、RSSI、扫描状态",
    "interaction": "选择、刷新、取消",
    "logic": "多设备必须主动选择，不自动绑定最强信号",
    "exception": "未授权、无设备、多设备、弱信号、断连、同步失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "双端已有；需完整空/多设备/弱信号状态"
  },
  {
    "id": "DEV-03",
    "group": "设备",
    "name": "首次绑定确认",
    "route": "Dialog",
    "priority": "P0",
    "parent": "DEV-02",
    "function": "确认首次绑定",
    "layout": "设备标识、风险说明、确认/取消",
    "data": "设备 ID、绑定状态",
    "interaction": "确认绑定、取消",
    "logic": "只有首次绑定调用绑定指令；普通重连不得清历史",
    "exception": "未授权、无设备、多设备、弱信号、断连、同步失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "iOS 有明确确认；Android 需行为等价"
  },
  {
    "id": "DEV-04",
    "group": "设备",
    "name": "佩戴引导",
    "route": "Sheet / Full Screen",
    "priority": "P0",
    "parent": "DEV-03 / 我的",
    "function": "解释佩戴与传感器方向",
    "layout": "图示、夜间佩戴、清洁说明",
    "data": "佩戴要点",
    "interaction": "继续、查看帮助",
    "logic": "不制造尺寸或松紧压力",
    "exception": "未授权、无设备、多设备、弱信号、断连、同步失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "iOS 有基础页；文案不得制造尺寸压力"
  },
  {
    "id": "DEV-05",
    "group": "设备",
    "name": "首次同步进度",
    "route": "`/device/initial-sync`",
    "priority": "P0",
    "parent": "DEV-03",
    "function": "完成首次历史同步",
    "layout": "分阶段进度、当前步骤、恢复动作",
    "data": "设备信息、历史批次、游标、质量",
    "interaction": "取消、稍后继续、分阶段重试",
    "logic": "批次幂等；中断保留成功游标",
    "exception": "未授权、无设备、多设备、弱信号、断连、同步失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "双端有同步状态，需分阶段与失败恢复"
  },
  {
    "id": "RHY-00",
    "group": "节律",
    "name": "节律基础设置",
    "route": "`/rhythm/setup`",
    "priority": "P0 可跳过",
    "parent": "DEV-05 / 节律",
    "function": "可选建立节律基础",
    "layout": "日期、平均周期、持续天数、跳过",
    "data": "用户输入的节律日期与参数",
    "interaction": "保存、跳过",
    "logic": "不询问更年期/绝经；跳过不影响核心能力",
    "exception": "未设置、日期冲突、暂停、删除、数据不足",
    "ios": "已有基础，需按新文案收口",
    "android": "缺失或不完整，需补齐",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "阶段、可能关联、提醒与删除",
    "backend": "节律摘要可选",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "iOS 有基础设置；Android 缺失"
  },
  {
    "id": "ONB-02",
    "group": "首次使用",
    "name": "身体天气建立中",
    "route": "`/today?state=building`",
    "priority": "P0 状态",
    "parent": "RHY-00",
    "function": "完成首次进入、授权、连接和同步",
    "layout": "单一任务优先；必要说明与恢复动作",
    "data": "账号、权限、设备或同步状态",
    "interaction": "继续、返回、重试",
    "logic": "状态机驱动，不以页面出现视为完成",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "使用今日页状态，不另做功能孤岛"
  },
  {
    "id": "TOD-01",
    "group": "今日",
    "name": "今日首页",
    "route": "`/today`",
    "priority": "P0",
    "parent": "Tab",
    "function": "一眼看懂今天如何安排",
    "layout": "大状态主视觉、三信号、一主行动、Halo 轻入口",
    "data": "状态名、一句结论、动态三信号、更新时间",
    "interaction": "进详情、点信号、进 Halo、刷新",
    "logic": "早晨主状态稳定；首页不显示总分和原始指标墙",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "一句结论、三个信号、一个主行动；未绑定沿用同版式与槽位且无模拟值；可显示今日灵感轻卡"
  },
  {
    "id": "TOD-02",
    "group": "今日",
    "name": "主观状态轻记录",
    "route": "Bottom Sheet",
    "priority": "P1",
    "parent": "TOD-01",
    "function": "补充当天主观感受",
    "layout": "一问、轻标签、跳过/保存",
    "data": "疲惫、压力、情绪波动或平稳",
    "interaction": "选择、保存、删除当日记录",
    "logic": "只作建议辅助，不直接重写 Body Weather",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "疲惫/压力/情绪/平稳；不强制、不做疗效评分"
  },
  {
    "id": "TOD-03",
    "group": "今日",
    "name": "Body Weather 详情",
    "route": "`/today/body-weather`",
    "priority": "P0",
    "parent": "TOD-01",
    "function": "解释为什么并查看详细数据",
    "layout": "上半屏结论/原因/建议；下滑后详细数据",
    "data": "睡眠、HRV/静息心率、活动、质量、版本",
    "interaction": "展开数据、纠正本次解释、进夜间/趋势/Halo",
    "logic": "规则计算状态，LLM 只组织语言；用户纠正与设备事实分开保存并阻止错误解释进入记忆",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "六段详情；支持用户纠正主观解释，不改写戒指数据；压力与放松在页内展开"
  },
  {
    "id": "TOD-04",
    "group": "今日",
    "name": "状态趋势",
    "route": "`/today/body-weather/trend`",
    "priority": "P0 仅 7 日",
    "parent": "TOD-03",
    "function": "查看近期状态变化",
    "layout": "7 日状态分布和信号趋势",
    "data": "状态、睡眠、能量、活动/压力、缺口",
    "interaction": "切换信号、开关节律图层",
    "logic": "当前仅 7 日；不足不画假曲线",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "14/30 日为后续增强"
  },
  {
    "id": "TOD-05",
    "group": "今日",
    "name": "睡眠详情",
    "route": "`/today/sleep`",
    "priority": "P0",
    "parent": "TOD-03 / TOD-08",
    "function": "查看昨夜睡眠记录",
    "layout": "摘要、阶段、连续性、时间轴、质量",
    "data": "时长、入睡/醒来、阶段、体动、质量",
    "interaction": "展开、查看来源",
    "logic": "只展示有效数据并说明缺口",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "六段详情；昨夜记录、阶段、连续性、趋势、质量和行动"
  },
  {
    "id": "TOD-06",
    "group": "今日",
    "name": "身体能量详情",
    "route": "`/today/energy`",
    "priority": "P0",
    "parent": "TOD-03",
    "function": "理解身体能量",
    "layout": "状态解释、夜间 HRV 估算、个人基线、高低含义、自主神经科普、适用边界、趋势",
    "data": "signal_type、metric_type、interval_type、value_ms、window_seconds、night_aggregation、valid_intervals_pct、artifact_filter、algorithm_version、静息心率、个人基线",
    "interaction": "查看趋势和来源；展开了解数值较高、接近平时或较低时通常代表什么",
    "logic": "首页只表达身体能量状态；R01 光学戒指得到 PPI/PRV 估算而非 ECG RR/NN；生产值必须标明具体指标、窗口、筛选、夜间汇总与算法版本；仅与同算法同场景的个人历史比较",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "用户侧只解释数值含义、个人基线、自主神经和使用边界，不展示公式或算法流程。R01 协议单值只写 HRV(ms)，未定义 RMSSD/SDNN；Donni API可返回两者但当前未获生产放行，正式单值口径仍需算法与供应商确认"
  },
  {
    "id": "TOD-07",
    "group": "今日",
    "name": "活动适配详情",
    "route": "`/today/activity-fit`",
    "priority": "P0",
    "parent": "TOD-03",
    "function": "安排今天活动强度",
    "layout": "建议、理由、可选动作",
    "data": "活动量、近期负荷、睡眠/能量方向",
    "interaction": "接受建议、进夜间",
    "logic": "运动是辅助建议，不变成主功能",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "六段详情；戒指与手机去重，活动建议服从身体天气"
  },
  {
    "id": "TOD-08",
    "group": "今日",
    "name": "昨夜摘要",
    "route": "`/today/last-night`",
    "priority": "P0",
    "parent": "TOD-01",
    "function": "回看昨夜并完成次日轻复盘",
    "layout": "播放摘要、执行确认、主观帮助、同期变化、设备观察",
    "data": "内容、播放时长、停止原因、实际执行、主观帮助、同期变化、睡眠摘要",
    "interaction": "选择执行程度和主观感受、补充同期变化、保存或修改复盘",
    "logic": "点击、实际执行、主观帮助与客观变化分开记录；单次变化不归因",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "夜间播放、渐弱方式、睡眠摘要、唤醒结果与多次观察口径"
  },
  {
    "id": "TOD-09",
    "group": "今日",
    "name": "14 晚进度与报告",
    "route": "`/reports/14-nights`",
    "priority": "P0",
    "parent": "TOD-01 / TOD-08",
    "function": "完成 14 晚建立与报告",
    "layout": "进度、有效夜晚、阶段说明、报告",
    "data": "有效夜晚、基线状态、趋势摘要",
    "interaction": "查看缺口、打开报告",
    "logic": "3-6 初步、7 正式、14 修正",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "7 晚正式基线，14 晚修正并生成报告"
  },
  {
    "id": "TOD-10",
    "group": "今日",
    "name": "状态分享卡预览",
    "route": "`/share/body-weather`",
    "priority": "P1",
    "parent": "TOD-03 / TOD-09",
    "function": "解释今日状态",
    "layout": "结论优先，详情数据下沉",
    "data": "个人基线相关状态与来源",
    "interaction": "查看详情或采取行动",
    "logic": "规则版本化、缺数降级",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "不展示敏感数值"
  },
  {
    "id": "TOD-11",
    "group": "今日",
    "name": "数据来源与质量说明",
    "route": "Bottom Sheet",
    "priority": "P0",
    "parent": "TOD-03",
    "function": "解释今日状态",
    "layout": "结论优先，详情数据下沉",
    "data": "个人基线相关状态与来源",
    "interaction": "查看详情或采取行动",
    "logic": "规则版本化、缺数降级",
    "exception": "建立中、部分数据、过期、同步失败、未连接",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 历史数据 + 自研规则",
    "rules": "基线、数据质量、Body Weather、解释与降级",
    "backend": "状态规则/报告",
    "owner": "产品+算法+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "五阶段生命周期、来源优先级、去重、补同步、更新时间和健康边界"
  },
  {
    "id": "HLT-00",
    "name": "健康数据中心",
    "route": "`/health`",
    "priority": "P0",
    "parent": "TOD-03 / MY-01",
    "note": "汇总健康指标入口、更新时间、质量状态和受控能力",
    "group": "健康数据",
    "function": "汇总健康指标入口、更新时间、质量状态和受控能力",
    "layout": "汇总健康指标入口、更新时间、质量状态和受控能力",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "汇总健康指标入口、更新时间、质量状态和受控能力",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-01",
    "name": "24 小时心率趋势",
    "route": "`/health/heart-rate`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-06",
    "note": "全天曲线、静息/夜间摘要、个人基线和缺失时段",
    "group": "健康数据",
    "function": "全天曲线、静息/夜间摘要、个人基线和缺失时段",
    "layout": "全天曲线、静息/夜间摘要、个人基线和缺失时段",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "全天曲线、静息/夜间摘要、个人基线和缺失时段",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-02",
    "name": "夜间呼吸率趋势",
    "route": "`/health/respiration`",
    "priority": "P0",
    "parent": "HLT-00 / TOD-05",
    "note": "夜间趋势、置信度、有效时段和非诊断边界",
    "group": "健康数据",
    "function": "夜间趋势、置信度、有效时段和非诊断边界",
    "layout": "夜间趋势、置信度、有效时段和非诊断边界",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "夜间趋势、置信度、有效时段和非诊断边界",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-03",
    "name": "主动测量中心与历史",
    "route": "`/health/measure`",
    "priority": "P0",
    "parent": "HLT-00",
    "note": "心率/HRV、血氧、温度入口、最近结果和失败记录",
    "group": "健康数据",
    "function": "心率/HRV、血氧、温度入口、最近结果和失败记录",
    "layout": "心率/HRV、血氧、温度入口、最近结果和失败记录",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "心率/HRV、血氧、温度入口、最近结果和失败记录",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-04",
    "name": "主动测量过程与结果",
    "route": "`/health/measure/:type`",
    "priority": "P0",
    "parent": "HLT-03",
    "note": "佩戴检查、进度、成功、失败原因、重试、结果和来源质量",
    "group": "健康数据",
    "function": "佩戴检查、进度、成功、失败原因、重试、结果和来源质量",
    "layout": "佩戴检查、进度、成功、失败原因、重试、结果和来源质量",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "佩戴检查、进度、成功、失败原因、重试、结果和来源质量",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-05",
    "name": "血氧状态与趋势",
    "route": "`/health/spo2`",
    "priority": "P0 Gated",
    "parent": "HLT-00 / HLT-03",
    "note": "页面必须开发；数据展示由能力码、质量和用户开关控制",
    "group": "健康数据",
    "function": "页面必须开发；数据展示由能力码、质量和用户开关控制",
    "layout": "页面必须开发；数据展示由能力码、质量和用户开关控制",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "页面必须开发；数据展示由能力码、质量和用户开关控制",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HLT-06",
    "name": "皮肤温度状态与趋势",
    "route": "`/health/temperature`",
    "priority": "P0 Gated",
    "parent": "HLT-00 / HLT-03",
    "note": "相对个人基线展示，不等同核心体温或激素检测",
    "group": "健康数据",
    "function": "相对个人基线展示，不等同核心体温或激素检测",
    "layout": "相对个人基线展示，不等同核心体温或激素检测",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "相对个人基线展示，不等同核心体温或激素检测",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "NIG-01",
    "group": "夜间",
    "name": "今晚首页",
    "route": "`/night`",
    "priority": "P0",
    "parent": "Tab",
    "function": "选择并开始今晚陪伴",
    "layout": "一条主推荐、原因、开始、换一个",
    "data": "推荐内容、时长、形式、适合状态",
    "interaction": "开始、换一个、设置唤醒",
    "logic": "规则推荐队列；保留用户主动选择",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "一条主推荐、推荐原因、开始、换一个"
  },
  {
    "id": "NIG-02",
    "group": "夜间",
    "name": "内容详情",
    "route": "`/night/content/:id`",
    "priority": "P0",
    "parent": "NIG-01",
    "function": "了解并试听夜间内容",
    "layout": "封面、时长、形式、适合状态、专业说明",
    "data": "内容元数据、试听资源",
    "interaction": "试听、开始、收藏/反馈入口",
    "logic": "使用后次日一次轻反馈；不做疗效评分",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "时长、形式、适合状态、试听、专业说明"
  },
  {
    "id": "NIG-03",
    "group": "夜间",
    "name": "换一个",
    "route": "Bottom Sheet",
    "priority": "P0",
    "parent": "NIG-01",
    "function": "轻量更换推荐",
    "layout": "底部单列备选和筛选",
    "data": "推荐队列、内容类型",
    "interaction": "换单项、确认",
    "logic": "不展开成内容商城",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "保留用户选择；不展开成大内容商城"
  },
  {
    "id": "NIG-04",
    "group": "夜间",
    "name": "夜间播放器",
    "route": "`/night/player`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-02",
    "function": "在睡前低刺激播放",
    "layout": "极简主视觉、进度、暂停、音量、渐弱",
    "data": "播放进度、渐弱模式、连接/后台状态",
    "interaction": "播放、暂停、锁屏控制、结束",
    "logic": "默认手机计时渐弱；实时入睡仅能力门通过后开启",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "极简、后台/锁屏、暂停、进度、音量、渐弱状态"
  },
  {
    "id": "NIG-05",
    "group": "夜间",
    "name": "今晚内容序列",
    "route": "Bottom Sheet",
    "priority": "P1",
    "parent": "NIG-04",
    "function": "完成今晚内容与唤醒闭环",
    "layout": "低刺激深色画布、一个主操作",
    "data": "内容、播放、设备和闹钟状态",
    "interaction": "播放、设置、恢复",
    "logic": "系统能力与 R01 能力共同门控",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "单内容 P0；多内容队列在稳定后开放"
  },
  {
    "id": "NIG-06",
    "group": "夜间",
    "name": "唤醒设置",
    "route": "`/night/wake-settings`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-04",
    "function": "设置可靠唤醒",
    "layout": "最晚时间、可选窗口、声音、音量",
    "data": "时间、权限、声音 ID、能力状态",
    "interaction": "设置、保存、试听",
    "logic": "最终时间闹钟是默认兜底；浅睡窗口受能力门控",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "最晚时间、窗口、声音、试听、最大音量"
  },
  {
    "id": "NIG-07",
    "group": "夜间",
    "name": "唤醒声音选择",
    "route": "Bottom Sheet",
    "priority": "P0",
    "parent": "NIG-06",
    "function": "完成今晚内容与唤醒闭环",
    "layout": "低刺激深色画布、一个主操作",
    "data": "内容、播放、设备和闹钟状态",
    "interaction": "播放、设置、恢复",
    "logic": "系统能力与 R01 能力共同门控",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "固定 3—5 个声音，必须试听"
  },
  {
    "id": "NIG-08",
    "group": "夜间",
    "name": "闹钟响起",
    "route": "System Full Screen",
    "priority": "P0",
    "parent": "系统调度",
    "function": "关闭闹钟或再睡",
    "layout": "全屏时间、关闭、再睡 5 分钟",
    "data": "闹钟实例、调度来源",
    "interaction": "关闭、再睡",
    "logic": "不默认播放视频或额外声音；关闭进入今日",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "关闭、再睡 5 分钟；不默认播视频或额外声音"
  },
  {
    "id": "NIG-09",
    "group": "夜间",
    "name": "醒来承接",
    "route": "`/today?source=alarm`",
    "priority": "P0",
    "parent": "NIG-08",
    "function": "完成今晚内容与唤醒闭环",
    "layout": "低刺激深色画布、一个主操作",
    "data": "内容、播放、设备和闹钟状态",
    "interaction": "播放、设置、恢复",
    "logic": "系统能力与 R01 能力共同门控",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/闹钟；R01 实时能力可选",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "关闭闹钟后进入今日；生成失败时先显示建立中"
  },
  {
    "id": "NIG-10",
    "group": "夜间",
    "name": "最近夜间",
    "route": "`/night/recent`",
    "priority": "P1",
    "parent": "NIG-01 / 我的",
    "function": "回看最近夜间",
    "layout": "时间列表、内容、结果摘要",
    "data": "本地夜间记录、反馈状态",
    "interaction": "查看、删除",
    "logic": "本地优先且不自动删除",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "本地优先、不自动删除、用户可手动删除"
  },
  {
    "id": "NIG-11",
    "group": "夜间",
    "name": "夜间异常说明",
    "route": "Bottom Sheet",
    "priority": "P0",
    "parent": "NIG-01 / NIG-04",
    "function": "完成今晚内容与唤醒闭环",
    "layout": "低刺激深色画布、一个主操作",
    "data": "内容、播放、设备和闹钟状态",
    "interaction": "播放、设置、恢复",
    "logic": "系统能力与 R01 能力共同门控",
    "exception": "音频失败、后台受限、断连、闹钟权限/调度失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有部分基础，播放/唤醒需补齐",
    "sdk": "OS 音频/内容服务",
    "rules": "推荐队列、渐弱、唤醒兜底、记录",
    "backend": "内容/夜间记录",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "断连、低电量、后台限制、音频失败及降级"
  },
  {
    "id": "NIG-12",
    "name": "智能睡眠联动",
    "route": "`/night/smart-sleep-link`",
    "priority": "P0",
    "parent": "NIG-01 / NIG-06",
    "note": "入睡渐弱、浅睡窗口唤醒、最终时间兜底和实际执行方式",
    "group": "夜间",
    "function": "入睡渐弱、浅睡窗口唤醒、最终时间兜底和实际执行方式",
    "layout": "入睡渐弱、浅睡窗口唤醒、最终时间兜底和实际执行方式",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "入睡渐弱、浅睡窗口唤醒、最终时间兜底和实际执行方式",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "HAL-01",
    "group": "Halo AI",
    "name": "Halo 首页与对话",
    "route": "`/halo`",
    "priority": "P0",
    "parent": "Tab",
    "function": "承接状态并开始陪伴",
    "layout": "一个 Halo、可选的继续上次、状态摘要、推荐问题、消息流和固定输入区",
    "data": "授权后的 Body Weather/节律摘要",
    "interaction": "直接对话；页头查看历史；输入区记录感受；进行中的小计划按情境出现；可移除上下文",
    "logic": "首页以对话为主，不把历史、用户记录和小计划做成同级功能菜单；无数据也能基础聊天",
    "exception": "无上下文、超时、模型失败、内容安全、现实支持",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "Body Weather / 今日灵感上下文、推荐问题、消息流、支持方式和行动卡使用同一会话容器"
  },
  {
    "id": "HAL-02",
    "group": "Halo AI",
    "name": "会话与持续话题",
    "route": "`/halo/conversations`",
    "priority": "P0",
    "parent": "HAL-01",
    "function": "完成短文本对话",
    "layout": "消息流、生成状态、输入区、行动卡",
    "data": "短上下文、来源、回复状态",
    "interaction": "发送、停止、重试、打开行动卡",
    "logic": "AI Gateway；超时/失败/安全有明确降级",
    "exception": "无上下文、超时、模型失败、内容安全、现实支持",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "最近会话、搜索、继续、暂停、完成、归档和删除"
  },
  {
    "id": "HAL-03",
    "group": "Halo AI",
    "name": "Halo 记忆",
    "route": "`/halo/memory`",
    "priority": "P0",
    "parent": "HAL-01 / HAL-08",
    "function": "查看和控制当次上下文",
    "layout": "来源列表与开关",
    "data": "Body Weather、节律、夜间摘要来源",
    "interaction": "移除、确认",
    "logic": "移除后本次及后续请求不再携带",
    "exception": "无上下文、超时、模型失败、内容安全、现实支持",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "记忆提案、确认、纠正、暂停、单删和清空"
  },
  {
    "id": "HAL-04",
    "group": "Halo AI",
    "name": "主动陪伴设置",
    "route": "`/halo/proactive`",
    "priority": "P0",
    "parent": "HAL-01 / HAL-08",
    "function": "把解释落到 App 行动",
    "layout": "行动标题、理由、目标",
    "data": "目标路由、返回 token",
    "interaction": "打开、完成后返回",
    "logic": "执行由 App 完成，Halo 不伪装执行成功",
    "exception": "无上下文、超时、模型失败、内容安全、现实支持",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "早晨、睡前、自定义、静默时间和独立通知授权"
  },
  {
    "id": "HAL-05",
    "group": "Halo AI",
    "name": "情绪与感受记录",
    "route": "`/halo/feelings`",
    "priority": "P0",
    "parent": "HAL-01",
    "function": "获得解释或陪伴",
    "layout": "单一 Halo、状态与输入",
    "data": "授权上下文和对话状态",
    "interaction": "输入、选择、跳转",
    "logic": "AI Gateway + 规则安全兜底",
    "exception": "无上下文、超时、模型失败、内容安全、现实支持",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "情绪词、强度、身体感受、事件和近期变化"
  },
  {
    "id": "HAL-06",
    "group": "Halo AI",
    "name": "主题陪伴",
    "route": "`/halo/journeys`",
    "priority": "P0",
    "parent": "HAL-01",
    "function": "管理主题陪伴与今天的一小步",
    "layout": "主题状态、今天行动、进度与行动反馈",
    "data": "主题、难度、执行状态、未完成原因、连续未完成次数",
    "interaction": "完成、稍后、替换、不适合、暂停、继续和更换主题",
    "logic": "连续未执行只降低难度、不催补做；不适合时停止该主题提醒",
    "exception": "稍后、太难、不合时机、不想做、主题不适合",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "主题发现、今日一步、替换、稍后、降难度、不适合、暂停、完成和复盘均采用页面状态承接"
  },
  {
    "id": "HAL-07",
    "group": "Halo AI",
    "name": "Halo 数据与隐私",
    "route": "`/halo/data-privacy`",
    "priority": "P0",
    "parent": "HAL-01 / HAL-08",
    "function": "获得解释或陪伴",
    "layout": "单一 Halo、状态与输入",
    "data": "授权上下文和对话状态",
    "interaction": "输入、选择、跳转",
    "logic": "AI Gateway + 规则安全兜底",
    "exception": "无上下文、超时、模型失败、内容安全、现实支持",
    "ios": "已有轻版基础，需统一",
    "android": "缺失或不完整，需补齐",
    "sdk": "无戒指直连；AI Gateway",
    "rules": "上下文、Prompt、安全、失败兜底",
    "backend": "AI Gateway/安全",
    "owner": "AI+后端+双端",
    "source": "docs/product/app-specs/03、04",
    "note": "身体上下文、当次来源、记忆权限、撤回与删除"
  },
  {
    "id": "HAL-08",
    "name": "Halo 设置",
    "route": "`/halo/settings`",
    "priority": "P0",
    "parent": "HAL-01 / MY-01",
    "note": "语气、语音、通知、今日灵感独立开关与个性化状态、安全说明、反馈和人工帮助入口",
    "group": "Halo AI",
    "function": "语气、语音、通知、今日灵感独立开关与个性化状态、安全说明、反馈和人工帮助入口",
    "layout": "语气、语音、通知、今日灵感独立开关与个性化状态、安全说明、反馈和人工帮助入口",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "语气、语音、通知、今日灵感独立开关与个性化状态、安全说明、反馈和人工帮助入口",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "RHY-01",
    "group": "节律",
    "name": "节律首页",
    "route": "`/rhythm`",
    "priority": "P0",
    "parent": "Tab",
    "function": "理解身体节律可能关联",
    "layout": "阶段、可能关联、月历、轻建议",
    "data": "日期、阶段、睡眠/情绪/能量摘要",
    "interaction": "看阶段、选日期、进 Halo",
    "logic": "只说可能关联，不确定归因",
    "exception": "未设置、日期冲突、暂停、删除、数据不足",
    "ios": "已有基础，需按新文案收口",
    "android": "缺失或不完整，需补齐",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "阶段、可能关联、提醒与删除",
    "backend": "节律摘要可选",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "当前阶段、可能关联、月历、轻建议"
  },
  {
    "id": "RHY-02",
    "group": "节律",
    "name": "阶段解释",
    "route": "`/rhythm/stage`",
    "priority": "P0",
    "parent": "RHY-01",
    "function": "解释当前阶段",
    "layout": "阶段说明、三方向信号、建议",
    "data": "节律阶段和可用状态摘要",
    "interaction": "查看来源、进夜间/Halo",
    "logic": "中性表达，不做备孕或医疗预测",
    "exception": "未设置、日期冲突、暂停、删除、数据不足",
    "ios": "已有基础，需按新文案收口",
    "android": "缺失或不完整，需补齐",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "阶段、可能关联、提醒与删除",
    "backend": "节律摘要可选",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "睡眠、情绪、能量三方向；不做确定归因"
  },
  {
    "id": "RHY-03",
    "group": "节律",
    "name": "日期/感受详情",
    "route": "Bottom Sheet",
    "priority": "P1",
    "parent": "RHY-01",
    "function": "理解节律变化",
    "layout": "阶段、日历、可能关联",
    "data": "用户输入和状态摘要",
    "interaction": "查看、编辑、暂停",
    "logic": "中性表达、用户可控",
    "exception": "未设置、日期冲突、暂停、删除、数据不足",
    "ios": "已有基础，需按新文案收口",
    "android": "缺失或不完整，需补齐",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "阶段、可能关联、提醒与删除",
    "backend": "节律摘要可选",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "轻标签记录；不做完整症状日记"
  },
  {
    "id": "RHY-04",
    "group": "节律",
    "name": "节律设置",
    "route": "`/rhythm/settings`",
    "priority": "P0",
    "parent": "RHY-01 / 我的",
    "function": "管理节律数据和提醒",
    "layout": "日期参数、提醒、暂停/删除入口",
    "data": "用户输入、提醒状态",
    "interaction": "编辑、保存、暂停、删除",
    "logic": "暂停与删除语义分开",
    "exception": "未设置、日期冲突、暂停、删除、数据不足",
    "ios": "已有基础，需按新文案收口",
    "android": "缺失或不完整，需补齐",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "阶段、可能关联、提醒与删除",
    "backend": "节律摘要可选",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "编辑日期、平均周期、持续天数、提醒"
  },
  {
    "id": "RHY-05",
    "group": "节律",
    "name": "暂停与删除",
    "route": "Dialog / Bottom Sheet",
    "priority": "P0",
    "parent": "RHY-04",
    "function": "理解节律变化",
    "layout": "阶段、日历、可能关联",
    "data": "用户输入和状态摘要",
    "interaction": "查看、编辑、暂停",
    "logic": "中性表达、用户可控",
    "exception": "未设置、日期冲突、暂停、删除、数据不足",
    "ios": "已有基础，需按新文案收口",
    "android": "缺失或不完整，需补齐",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "阶段、可能关联、提醒与删除",
    "backend": "节律摘要可选",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "清楚说明暂停展示与删除数据的差异"
  },
  {
    "id": "RHY-06",
    "group": "节律",
    "name": "和 Halo 看看这段变化",
    "route": "Deep Link",
    "priority": "P0",
    "parent": "RHY-01 / RHY-02",
    "function": "理解节律变化",
    "layout": "阶段、日历、可能关联",
    "data": "用户输入和状态摘要",
    "interaction": "查看、编辑、暂停",
    "logic": "中性表达、用户可控",
    "exception": "未设置、日期冲突、暂停、删除、数据不足",
    "ios": "已有基础，需按新文案收口",
    "android": "缺失或不完整，需补齐",
    "sdk": "无；使用用户输入/状态摘要",
    "rules": "阶段、可能关联、提醒与删除",
    "backend": "节律摘要可选",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "用户主动带入摘要，允许移除"
  },
  {
    "id": "MY-01",
    "group": "我的",
    "name": "我的首页",
    "route": "`/me`",
    "priority": "P0",
    "parent": "Tab",
    "function": "管理账号、戒指和隐私",
    "layout": "账号头部；戒指、隐私、通知、帮助优先",
    "data": "账号摘要、设备状态、设置入口",
    "interaction": "进入各管理页",
    "logic": "商业权益入口只放第二层且受开关控制",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "账号、六级会员/Points、硬件三态、商城订单推荐边界、设备、Studio、隐私和帮助"
  },
  {
    "id": "ACC-01",
    "group": "我的",
    "name": "个人资料",
    "route": "`/me/profile`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理账号、设备或支持事项",
    "layout": "列表/表单围绕单一管理任务",
    "data": "账号、设置或设备事实",
    "interaction": "查看、编辑、提交",
    "logic": "以后端和系统状态为准",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "昵称、头像、生日等最小资料；生日营销另行同意"
  },
  {
    "id": "DEV-10",
    "group": "设备",
    "name": "我的 Halo 硬件",
    "route": "`/me/device`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理已绑定戒指",
    "layout": "连接、电量、同步、设备操作",
    "data": "设备 ID、电量、同步、绑定、能力",
    "interaction": "连接、同步、查看信息、移除",
    "logic": "无响铃/震动/亮灯查找；只保留最后连接线索",
    "exception": "未授权、无设备、多设备、弱信号、断连、同步失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "支持多款硬件；通用任务按账号行为去重；设备详情不占底部 Tab"
  },
  {
    "id": "DEV-11",
    "group": "设备",
    "name": "设备信息",
    "route": "`/me/device/info`",
    "priority": "P0",
    "parent": "DEV-10",
    "function": "查看设备事实",
    "layout": "设备、固件/硬件、能力状态",
    "data": "版本、电量、最后同步、能力码",
    "interaction": "复制信息、检查更新",
    "logic": "展示真实回调与能力，不按 SDK 方法猜测",
    "exception": "未授权、无设备、多设备、弱信号、断连、同步失败",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "R01 BLE SDK",
    "rules": "连接/绑定/重连/同步状态机",
    "backend": "设备绑定/同步游标",
    "owner": "SDK+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "电量、同步、固件/硬件版本、绑定状态、能力状态"
  },
  {
    "id": "DEV-12",
    "name": "高级设备操作",
    "route": "`/me/device/advanced`",
    "priority": "P0",
    "parent": "DEV-10",
    "note": "清空戒指缓存、重置今日步数、恢复出厂；逐项说明影响并执行强确认",
    "group": "设备",
    "function": "清空戒指缓存、重置今日步数、恢复出厂；逐项说明影响并执行强确认",
    "layout": "清空戒指缓存、重置今日步数、恢复出厂；逐项说明影响并执行强确认",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "清空戒指缓存、重置今日步数、恢复出厂；逐项说明影响并执行强确认",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "戒指 SDK / 系统能力",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "SET-01",
    "group": "我的",
    "name": "数据与隐私",
    "route": "`/me/data-privacy`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "控制健康与 AI 数据",
    "layout": "授权、来源、本地/云说明、导出/删除",
    "data": "授权状态、保存位置、删除任务",
    "interaction": "撤回、导出、删除",
    "logic": "云端仅必要摘要；注销不能只清本地",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "权限、数据来源、本地/云摘要、删除与导出说明"
  },
  {
    "id": "SET-02",
    "group": "我的",
    "name": "通知与夜间设置",
    "route": "`/me/notifications-night`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理通知和夜间行为",
    "layout": "提醒开关、静默时间、系统状态",
    "data": "通知/闹钟权限、提醒设置",
    "interaction": "开关、去系统设置、试听",
    "logic": "权限关闭时展示真实影响",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "睡前、早晨、低电量、同步、报告、静默时间"
  },
  {
    "id": "SET-03",
    "group": "我的",
    "name": "通用设置",
    "route": "`/me/settings`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理通用体验",
    "layout": "语言、显示、降低动态、Halo 语气",
    "data": "偏好和系统能力",
    "interaction": "设置、恢复默认",
    "logic": "语气偏好不等于人格切换",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "语言、显示、降低动态、Halo 语气偏好"
  },
  {
    "id": "HELP-01",
    "group": "我的",
    "name": "使用帮助/FAQ",
    "route": "`/me/help`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理账号、设备或支持事项",
    "layout": "列表/表单围绕单一管理任务",
    "data": "账号、设置或设备事实",
    "interaction": "查看、编辑、提交",
    "logic": "以后端和系统状态为准",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "登录、连接、同步、夜间、数据解释、售后"
  },
  {
    "id": "HELP-02",
    "group": "我的",
    "name": "问题反馈",
    "route": "`/me/feedback`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "提交可追踪问题",
    "layout": "类型、描述、截图、日志授权、结果",
    "data": "问题、附件、日志授权",
    "interaction": "提交、撤回附件、查看结果",
    "logic": "默认不上传健康明细；日志需单独授权",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "类型、描述、截图、日志授权、提交结果"
  },
  {
    "id": "HELP-03",
    "group": "我的",
    "name": "企业微信人工客服",
    "route": "WeCom SDK / System",
    "priority": "P0",
    "parent": "HELP-01 / HAL-06",
    "function": "管理账号、设备或支持事项",
    "layout": "列表/表单围绕单一管理任务",
    "data": "账号、设置或设备事实",
    "interaction": "查看、编辑、提交",
    "logic": "以后端和系统状态为准",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "短时 `service_ticket`；冲正申诉复用；URL 与埋点不携带业务/健康/自由文本"
  },
  {
    "id": "LEGAL-02",
    "group": "首次使用",
    "name": "关于与协议",
    "route": "`/me/about-legal`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理账号、设备或支持事项",
    "layout": "列表/表单围绕单一管理任务",
    "data": "账号、设置或设备事实",
    "interaction": "查看、编辑、提交",
    "logic": "以后端和系统状态为准",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "版本号、隐私、用户协议、健康/AI边界、主体信息"
  },
  {
    "id": "ACC-02",
    "group": "我的",
    "name": "账号安全",
    "route": "`/me/account`",
    "priority": "P0",
    "parent": "MY-01",
    "function": "管理账号安全",
    "layout": "手机号、退出、注销入口",
    "data": "账号状态和安全事件",
    "interaction": "退出、注销",
    "logic": "退出不删除数据；注销走后端状态机",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "手机号、退出、便捷注销；注销不可只清本地"
  },
  {
    "id": "ACC-03",
    "group": "我的",
    "name": "注销确认与结果",
    "route": "Full Screen / Dialog",
    "priority": "P0",
    "parent": "ACC-02",
    "function": "确认并完成注销",
    "layout": "影响说明、二次确认、处理结果",
    "data": "删除范围、任务状态、时间",
    "interaction": "确认、取消、重试、客服",
    "logic": "服务端执行且可审计；失败可恢复",
    "exception": "加载、空、失败、离线、权限不足",
    "ios": "已有基础，需逐页验收",
    "android": "已有基础，需调整",
    "sdk": "无或系统能力",
    "rules": "账号、权限或页面状态机",
    "backend": "配置/账号/客服",
    "owner": "产品+双端+后端",
    "source": "docs/product/app-specs/03、04",
    "note": "资产快照、即时/最长15工作日、继续履约、数据删除/留存、失败恢复"
  },
  {
    "id": "STU-08",
    "name": "Halo Studio 首页",
    "route": "`/me/studio`",
    "priority": "P0",
    "parent": "MY-01 / Deep Link",
    "note": "已预约、受邀、扫码和官方精选；不申请定位、不做附近找店",
    "group": "Halo Studio",
    "function": "已预约、受邀、扫码和官方精选；不申请定位、不做附近找店",
    "layout": "已预约、受邀、扫码和官方精选；不申请定位、不做附近找店",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "已预约、受邀、扫码和官方精选；不申请定位、不做附近找店",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-01",
    "name": "扫码或输入体验码",
    "route": "`/me/studio/code`",
    "priority": "P0",
    "parent": "STU-08 / Deep Link",
    "note": "只解析 Studio 命名空间；体验来源不等于订单归因",
    "group": "Halo Studio",
    "function": "只解析 Studio 命名空间；体验来源不等于订单归因",
    "layout": "只解析 Studio 命名空间；体验来源不等于订单归因",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "只解析 Studio 命名空间；体验来源不等于订单归因",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-09",
    "name": "活动详情",
    "route": "`/me/studio/experiences/:id`",
    "priority": "P0",
    "parent": "STU-08 / STU-01",
    "note": "仅瑜伽、普拉提、冥想；显示价格、名额、取消和数据边界",
    "group": "Halo Studio",
    "function": "仅瑜伽、普拉提、冥想；显示价格、名额、取消和数据边界",
    "layout": "仅瑜伽、普拉提、冥想；显示价格、名额、取消和数据边界",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "仅瑜伽、普拉提、冥想；显示价格、名额、取消和数据边界",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-02",
    "name": "课程/活动确认",
    "route": "`/me/studio/experiences/:id/confirm`",
    "priority": "P0",
    "parent": "STU-01 / STU-09",
    "note": "冻结机构、地点、场次、能力、价格和取消规则快照",
    "group": "Halo Studio",
    "function": "冻结机构、地点、场次、能力、价格和取消规则快照",
    "layout": "冻结机构、地点、场次、能力、价格和取消规则快照",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "冻结机构、地点、场次、能力、价格和取消规则快照",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-16",
    "name": "会员预约确认",
    "route": "`/me/studio/experiences/:id/book`",
    "priority": "P0",
    "parent": "STU-09",
    "note": "Halo Member 资格、名额、座位锁定、免费/付费分支",
    "group": "Halo Studio",
    "function": "Halo Member 资格、名额、座位锁定、免费/付费分支",
    "layout": "Halo Member 资格、名额、座位锁定、免费/付费分支",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "Halo Member 资格、名额、座位锁定、免费/付费分支",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-17",
    "name": "Studio 支付与结果",
    "route": "`/me/studio/orders/:id/pay`",
    "priority": "P0",
    "parent": "STU-16",
    "note": "单次活动订单；无购物车、地址、物流和商品库存",
    "group": "Halo Studio",
    "function": "单次活动订单；无购物车、地址、物流和商品库存",
    "layout": "单次活动订单；无购物车、地址、物流和商品库存",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "单次活动订单；无购物车、地址、物流和商品库存",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-18",
    "name": "我的预约与退款",
    "route": "`/me/studio/bookings/:id`",
    "priority": "P0",
    "parent": "STU-08 / STU-17",
    "note": "预约、支付、取消、退款、外部机构来源和客服责任",
    "group": "Halo Studio",
    "function": "预约、支付、取消、退款、外部机构来源和客服责任",
    "layout": "预约、支付、取消、退款、外部机构来源和客服责任",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "预约、支付、取消、退款、外部机构来源和客服责任",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-10",
    "name": "参与模式与同意",
    "route": "`/me/studio/participations/:id/consent`",
    "priority": "P0",
    "parent": "STU-02 / STU-18",
    "note": "七种 ConsentPurpose 分别授权；拒绝可选项不阻断基础参与",
    "group": "Halo Studio",
    "function": "七种 ConsentPurpose 分别授权；拒绝可选项不阻断基础参与",
    "layout": "七种 ConsentPurpose 分别授权；拒绝可选项不阻断基础参与",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "七种 ConsentPurpose 分别授权；拒绝可选项不阻断基础参与",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-11",
    "name": "课前意图与感受",
    "route": "`/me/studio/participations/:id/reflection`",
    "priority": "P0",
    "parent": "STU-10",
    "note": "页面属于 1.0 P0，但填写内容可跳过；只用于本人报告和 Halo 承接",
    "group": "Halo Studio",
    "function": "页面属于 1.0 P0，但填写内容可跳过；只用于本人报告和 Halo 承接",
    "layout": "页面属于 1.0 P0，但填写内容可跳过；只用于本人报告和 Halo 承接",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "页面属于 1.0 P0，但填写内容可跳过；只用于本人报告和 Halo 承接",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-03",
    "name": "课前准备",
    "route": "`/me/studio/participations/:id/preflight`",
    "priority": "P0",
    "parent": "STU-10 / STU-11",
    "note": "本人戒指、连接、电量、佩戴和数据质量门禁",
    "group": "Halo Studio",
    "function": "本人戒指、连接、电量、佩戴和数据质量门禁",
    "layout": "本人戒指、连接、电量、佩戴和数据质量门禁",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "本人戒指、连接、电量、佩戴和数据质量门禁",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-04",
    "name": "记录中",
    "route": "`/me/studio/sessions/:id`",
    "priority": "P0",
    "parent": "STU-03",
    "note": "低打扰记录；不展示实时健康数值；支持恢复与降级",
    "group": "Halo Studio",
    "function": "低打扰记录；不展示实时健康数值；支持恢复与降级",
    "layout": "低打扰记录；不展示实时健康数值；支持恢复与降级",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "低打扰记录；不展示实时健康数值；支持恢复与降级",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-12",
    "name": "报告状态",
    "route": "`/me/studio/participations/:id/report-status`",
    "priority": "P0",
    "parent": "STU-04 / STU-08",
    "note": "等待、不足、失败、重试、撤回和替代状态",
    "group": "Halo Studio",
    "function": "等待、不足、失败、重试、撤回和替代状态",
    "layout": "等待、不足、失败、重试、撤回和替代状态",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "等待、不足、失败、重试、撤回和替代状态",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-05",
    "name": "课后轻报告",
    "route": "`/me/studio/participations/:id/post-report`",
    "priority": "P0",
    "parent": "STU-12",
    "note": "方向性观察，不证明课程效果",
    "group": "Halo Studio",
    "function": "方向性观察，不证明课程效果",
    "layout": "方向性观察，不证明课程效果",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "方向性观察，不证明课程效果",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-06",
    "name": "次日完整报告",
    "route": "`/me/studio/participations/:id/next-day-report`",
    "priority": "P0",
    "parent": "STU-12 / STU-08",
    "note": "睡眠、Body Weather、基线和授权均满足才生成",
    "group": "Halo Studio",
    "function": "睡眠、Body Weather、基线和授权均满足才生成",
    "layout": "睡眠、Body Weather、基线和授权均满足才生成",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "睡眠、Body Weather、基线和授权均满足才生成",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-13",
    "name": "权益到账",
    "route": "`/me/studio/participations/:id/benefit`",
    "priority": "P0",
    "parent": "STU-05 / STU-06",
    "note": "BenefitRule 版本化、幂等，积分与现金收益分账",
    "group": "Halo Studio",
    "function": "BenefitRule 版本化、幂等，积分与现金收益分账",
    "layout": "BenefitRule 版本化、幂等，积分与现金收益分账",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "BenefitRule 版本化、幂等，积分与现金收益分账",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-14",
    "name": "活动关联与联系设置",
    "route": "`/me/studio/participations/:id/contact`",
    "priority": "P0",
    "parent": "STU-15",
    "note": "机构联系仅受控中继，不开放手机号、微信或名单导出",
    "group": "Halo Studio",
    "function": "机构联系仅受控中继，不开放手机号、微信或名单导出",
    "layout": "机构联系仅受控中继，不开放手机号、微信或名单导出",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "机构联系仅受控中继，不开放手机号、微信或名单导出",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-07",
    "name": "最近体验",
    "route": "`/me/studio/history`",
    "priority": "P0",
    "parent": "STU-08",
    "note": "最近记录、报告状态、预约来源和删除入口",
    "group": "Halo Studio",
    "function": "最近记录、报告状态、预约来源和删除入口",
    "layout": "最近记录、报告状态、预约来源和删除入口",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "最近记录、报告状态、预约来源和删除入口",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  },
  {
    "id": "STU-15",
    "name": "单次体验详情与删除",
    "route": "`/me/studio/participations/:id`",
    "priority": "P0",
    "parent": "STU-07 / STU-08",
    "note": "区分本地删除、云端隐私请求、匿名聚合和法定留存",
    "group": "Halo Studio",
    "function": "区分本地删除、云端隐私请求、匿名聚合和法定留存",
    "layout": "区分本地删除、云端隐私请求、匿名聚合和法定留存",
    "data": "按页面场景显示必要状态、来源与更新时间",
    "interaction": "完成主任务，并提供返回、取消或恢复动作",
    "logic": "区分本地删除、云端隐私请求、匿名聚合和法定留存",
    "exception": "加载、空、失败、离线与权限不足均需可恢复",
    "sdk": "无强制硬件 SDK",
    "rules": "页面状态机与健康表达边界",
    "backend": "配置、账号或业务服务",
    "owner": "产品 + 双端 + 后端",
    "source": "docs/product/app-specs/02、03"
  }
];
